(define (problem problem_2)
    (:domain sokoban)
    (:objects
        sq-a1 sq-a2 sq-a3 sq-a4 sq-a5 sq-a6 sq-a7 sq-a8 sq-b1 sq-b2 sq-b3 sq-b4 sq-b5 sq-b6 sq-b7 sq-b8 sq-c1 sq-c2 sq-c3 sq-c4 sq-c5 sq-c6 sq-c7 sq-c8 sq-d1 sq-d2 sq-d3 sq-d4 sq-d5 sq-d6 sq-d7 sq-d8 sq-e1 sq-e2 sq-e3 sq-e4 sq-e5 sq-e6 sq-e7 sq-e8 sq-f1 sq-f2 sq-f3 sq-f4 sq-f5 sq-f6 sq-f7 sq-f8 sq-g1 sq-g2 sq-g3 sq-g4 sq-g5 sq-g6 sq-g7 sq-g8 sq-h1 sq-h2 sq-h3 sq-h4 sq-h5 sq-h6 sq-h7 sq-h8 - square
        b1 b2 b3 b4 - box 
    )
    (:init
        ;todo: put the initial state's facts and numeric values here
        ;8*8 grid
        (above sq-a1 sq-a2)
        (above sq-a2 sq-a3)
        (above sq-a3 sq-a4)
        (above sq-a4 sq-a5)
        (above sq-a5 sq-a6)
        (above sq-a6 sq-a7)
        (above sq-a7 sq-a8)
        (above sq-b1 sq-b2)
        (above sq-b2 sq-b3)
        (above sq-b3 sq-b4)
        (above sq-b4 sq-b5)
        (above sq-b5 sq-b6)
        (above sq-b6 sq-b7)
        (above sq-b7 sq-b8)
        (above sq-c1 sq-c2)
        (above sq-c2 sq-c3)
        (above sq-c3 sq-c4)
        (above sq-c4 sq-c5)
        (above sq-c5 sq-c6)
        (above sq-c6 sq-c7)
        (above sq-c7 sq-c8)
        (above sq-d1 sq-d2)
        (above sq-d2 sq-d3)
        (above sq-d3 sq-d4)
        (above sq-d4 sq-d5)
        (above sq-d5 sq-d6)
        (above sq-d6 sq-d7)
        (above sq-d7 sq-d8)
        (above sq-e1 sq-e2)
        (above sq-e2 sq-e3)
        (above sq-e3 sq-e4)
        (above sq-e4 sq-e5)
        (above sq-e5 sq-e6)
        (above sq-e6 sq-e7)
        (above sq-e7 sq-e8)
        (above sq-f1 sq-f2)
        (above sq-f2 sq-f3)
        (above sq-f3 sq-f4)
        (above sq-f4 sq-f5)
        (above sq-f5 sq-f6)
        (above sq-f6 sq-f7)
        (above sq-f7 sq-f8)
        (above sq-g1 sq-g2)
        (above sq-g2 sq-g3)
        (above sq-g3 sq-g4)
        (above sq-g4 sq-g5)
        (above sq-g5 sq-g6)
        (above sq-g6 sq-g7)
        (above sq-g7 sq-g8)
        (above sq-h1 sq-h2)
        (above sq-h2 sq-h3)
        (above sq-h3 sq-h4)
        (above sq-h4 sq-h5)
        (above sq-h5 sq-h6)
        (above sq-h6 sq-h7)
        (above sq-h7 sq-h8)

        ; (below sq-a2 sq-a1)
        ; (below sq-a3 sq-a2)
        ; (below sq-a4 sq-a3)
        ; (below sq-a5 sq-a4)
        ; (below sq-a6 sq-a5)
        ; (below sq-a7 sq-a6)
        ; (below sq-a8 sq-a7)
        ; (below sq-b2 sq-b1)
        ; (below sq-b3 sq-b2)
        ; (below sq-b4 sq-b3)
        ; (below sq-b5 sq-b4)
        ; (below sq-b6 sq-b5)
        ; (below sq-b7 sq-b6)
        ; (below sq-b8 sq-b7)
        ; (below sq-c2 sq-c1)
        ; (below sq-c3 sq-c2)
        ; (below sq-c4 sq-c3)
        ; (below sq-c5 sq-c4)
        ; (below sq-c6 sq-c5)
        ; (below sq-c7 sq-c6)
        ; (below sq-c8 sq-c7)
        ; (below sq-d2 sq-d1)
        ; (below sq-d3 sq-d2)
        ; (below sq-d4 sq-d3)
        ; (below sq-d5 sq-d4)
        ; (below sq-d6 sq-d5)
        ; (below sq-d7 sq-d6)
        ; (below sq-d8 sq-d7)
        ; (below sq-e2 sq-e1)
        ; (below sq-e3 sq-e2)
        ; (below sq-e4 sq-e3)
        ; (below sq-e5 sq-e4)
        ; (below sq-e6 sq-e5)
        ; (below sq-e7 sq-e6)
        ; (below sq-e8 sq-e7)
        ; (below sq-f2 sq-f1)
        ; (below sq-f3 sq-f2)
        ; (below sq-f4 sq-f3)
        ; (below sq-f5 sq-f4)
        ; (below sq-f6 sq-f5)
        ; (below sq-f7 sq-f6)
        ; (below sq-f8 sq-f7)
        ; (below sq-g2 sq-g1)
        ; (below sq-g3 sq-g2)
        ; (below sq-g4 sq-g3)
        ; (below sq-g5 sq-g4)
        ; (below sq-g6 sq-g5)
        ; (below sq-g7 sq-g6)
        ; (below sq-g8 sq-g7)
        ; (below sq-h2 sq-h1)
        ; (below sq-h3 sq-h2)
        ; (below sq-h4 sq-h3)
        ; (below sq-h5 sq-h4)
        ; (below sq-h6 sq-h5)
        ; (below sq-h7 sq-h6)
        ; (below sq-h8 sq-h7)

        (left-to sq-a1 sq-b1)
        (left-to sq-a2 sq-b2)
        (left-to sq-a3 sq-b3)
        (left-to sq-a4 sq-b4)
        (left-to sq-a5 sq-b5)
        (left-to sq-a6 sq-b6)
        (left-to sq-a7 sq-b7)
        (left-to sq-a8 sq-b8)
        (left-to sq-b1 sq-c1)
        (left-to sq-b2 sq-c2)
        (left-to sq-b3 sq-c3)
        (left-to sq-b4 sq-c4)
        (left-to sq-b5 sq-c5)
        (left-to sq-b6 sq-c6)
        (left-to sq-b7 sq-c7)
        (left-to sq-b8 sq-c8)
        (left-to sq-c1 sq-d1)
        (left-to sq-c2 sq-d2)
        (left-to sq-c3 sq-d3)
        (left-to sq-c4 sq-d4)
        (left-to sq-c5 sq-d5)
        (left-to sq-c6 sq-d6)
        (left-to sq-c7 sq-d7)
        (left-to sq-c8 sq-d8)
        (left-to sq-d1 sq-e1)
        (left-to sq-d2 sq-e2)
        (left-to sq-d3 sq-e3)
        (left-to sq-d4 sq-e4)
        (left-to sq-d5 sq-e5)
        (left-to sq-d6 sq-e6)
        (left-to sq-d7 sq-e7)
        (left-to sq-d8 sq-e8)
        (left-to sq-e1 sq-f1)
        (left-to sq-e2 sq-f2)
        (left-to sq-e3 sq-f3)
        (left-to sq-e4 sq-f4)
        (left-to sq-e5 sq-f5)
        (left-to sq-e6 sq-f6)
        (left-to sq-e7 sq-f7)
        (left-to sq-e8 sq-f8)
        (left-to sq-f1 sq-g1)
        (left-to sq-f2 sq-g2)
        (left-to sq-f3 sq-g3)
        (left-to sq-f4 sq-g4)
        (left-to sq-f5 sq-g5)
        (left-to sq-f6 sq-g6)
        (left-to sq-f7 sq-g7)
        (left-to sq-f8 sq-g8)
        (left-to sq-g1 sq-h1)
        (left-to sq-g2 sq-h2)
        (left-to sq-g3 sq-h3)
        (left-to sq-g4 sq-h4)
        (left-to sq-g5 sq-h5)
        (left-to sq-g6 sq-h6)
        (left-to sq-g7 sq-h7)
        (left-to sq-g8 sq-h8)

        ; (right-to sq-b1 sq-a1)
        ; (right-to sq-b2 sq-a2)
        ; (right-to sq-b3 sq-a3)
        ; (right-to sq-b4 sq-a4)
        ; (right-to sq-b5 sq-a5)
        ; (right-to sq-b6 sq-a6)
        ; (right-to sq-b7 sq-a7)
        ; (right-to sq-b8 sq-a8)
        ; (right-to sq-c1 sq-b1)
        ; (right-to sq-c2 sq-b2)
        ; (right-to sq-c3 sq-b3)
        ; (right-to sq-c4 sq-b4)
        ; (right-to sq-c5 sq-b5)
        ; (right-to sq-c6 sq-b6)
        ; (right-to sq-c7 sq-b7)
        ; (right-to sq-c8 sq-b8)
        ; (right-to sq-d1 sq-c1)
        ; (right-to sq-d2 sq-c2)
        ; (right-to sq-d3 sq-c3)
        ; (right-to sq-d4 sq-c4)
        ; (right-to sq-d5 sq-c5)
        ; (right-to sq-d6 sq-c6)
        ; (right-to sq-d7 sq-c7)
        ; (right-to sq-d8 sq-c8)
        ; (right-to sq-e1 sq-d1)
        ; (right-to sq-e2 sq-d2)
        ; (right-to sq-e3 sq-d3)
        ; (right-to sq-e4 sq-d4)
        ; (right-to sq-e5 sq-d5)
        ; (right-to sq-e6 sq-d6)
        ; (right-to sq-e7 sq-d7)
        ; (right-to sq-e8 sq-d8)
        ; (right-to sq-f1 sq-e1)
        ; (right-to sq-f2 sq-e2)
        ; (right-to sq-f3 sq-e3)
        ; (right-to sq-f4 sq-e4)
        ; (right-to sq-f5 sq-e5)
        ; (right-to sq-f6 sq-e6)
        ; (right-to sq-f7 sq-e7)
        ; (right-to sq-f8 sq-e8)
        ; (right-to sq-g1 sq-f1)
        ; (right-to sq-g2 sq-f2)
        ; (right-to sq-g3 sq-f3)
        ; (right-to sq-g4 sq-f4)
        ; (right-to sq-g5 sq-f5)
        ; (right-to sq-g6 sq-f6)
        ; (right-to sq-g7 sq-f7)
        ; (right-to sq-g8 sq-f8)
        ; (right-to sq-h1 sq-g1)
        ; (right-to sq-h2 sq-g2)
        ; (right-to sq-h3 sq-g3)
        ; (right-to sq-h4 sq-g4)
        ; (right-to sq-h5 sq-g5)
        ; (right-to sq-h6 sq-g6)
        ; (right-to sq-h7 sq-g7)
        ; (right-to sq-h8 sq-g8)
  
        (is-free sq-d2)
        (is-free sq-d3)
        (is-free sq-e4)
        (is-free sq-g4)
        (is-free sq-b5)
        (is-free sq-d5)
        (is-free sq-e5)
        (is-free sq-e6)
        (is-free sq-e7)

        ; is-wall 
        (is-wall sq-a1)
        (is-wall sq-a2)
        (is-wall sq-a3)
        (is-wall sq-a4)
        (is-wall sq-a5)
        (is-wall sq-a6)
        (is-wall sq-a7)
        (is-wall sq-a8)
        (is-wall sq-b1)
        (is-wall sq-b2)
        (is-wall sq-b3)
        (is-wall sq-b4)
        (is-wall sq-b6)
        (is-wall sq-b7)
        (is-wall sq-b8)
        (is-wall sq-c1)
        (is-wall sq-c2)
        (is-wall sq-c3)
        (is-wall sq-c4)
        (is-wall sq-c6)
        (is-wall sq-c7)
        (is-wall sq-c8)
        (is-wall sq-d1)
        (is-wall sq-d6)
        (is-wall sq-d7)
        (is-wall sq-d8)
        (is-wall sq-e1)
        (is-wall sq-e2)
        (is-wall sq-e3)
        (is-wall sq-e8)
        (is-wall sq-f1)
        (is-wall sq-f2)
        (is-wall sq-f3)
        (is-wall sq-f5)
        (is-wall sq-f6)
        (is-wall sq-f7)
        (is-wall sq-f8)
        (is-wall sq-g1)
        (is-wall sq-g2)
        (is-wall sq-g3)
        (is-wall sq-g5)
        (is-wall sq-g6)
        (is-wall sq-g7)
        (is-wall sq-g8)
        (is-wall sq-h1)
        (is-wall sq-h2)
        (is-wall sq-h3)
        (is-wall sq-h4)
        (is-wall sq-h5)
        (is-wall sq-h6)
        (is-wall sq-h7)
        (is-wall sq-h8)

        (box-at b1 sq-d4)
        (box-at b2 sq-f4)
        (box-at b3 sq-c5)
        (box-at b4 sq-e6)

        (hole-at sq-d2)
        (hole-at sq-g4)
        (hole-at sq-b5)
        (hole-at sq-e7)

        (no-hole-at sq-a1)
        (no-hole-at sq-a2)
        (no-hole-at sq-a3)
        (no-hole-at sq-a4)
        (no-hole-at sq-a5)
        (no-hole-at sq-a6)
        (no-hole-at sq-a7)
        (no-hole-at sq-a8)
        (no-hole-at sq-b1)
        (no-hole-at sq-b2)
        (no-hole-at sq-b3)
        (no-hole-at sq-b4)
        (no-hole-at sq-b6)
        (no-hole-at sq-b7)
        (no-hole-at sq-b8)
        (no-hole-at sq-c1)
        (no-hole-at sq-c2)
        (no-hole-at sq-c3)
        (no-hole-at sq-c4)
        (no-hole-at sq-c5)
        (no-hole-at sq-c6)
        (no-hole-at sq-c7)
        (no-hole-at sq-c8)
        (no-hole-at sq-d1)
        (no-hole-at sq-d3)
        (no-hole-at sq-d4)
        (no-hole-at sq-d5)
        (no-hole-at sq-d6)
        (no-hole-at sq-d7)
        (no-hole-at sq-d8)
        (no-hole-at sq-e1)
        (no-hole-at sq-e2)
        (no-hole-at sq-e3)
        (no-hole-at sq-e4)
        (no-hole-at sq-e5)
        (no-hole-at sq-e6)
        (no-hole-at sq-e8)
        (no-hole-at sq-f1)
        (no-hole-at sq-f2)
        (no-hole-at sq-f3)
        (no-hole-at sq-f4)
        (no-hole-at sq-f5)
        (no-hole-at sq-f6)
        (no-hole-at sq-f7)
        (no-hole-at sq-f8)
        (no-hole-at sq-g1)
        (no-hole-at sq-g2)
        (no-hole-at sq-g3)
        (no-hole-at sq-g5)
        (no-hole-at sq-g6)
        (no-hole-at sq-g7)
        (no-hole-at sq-g8)
        (no-hole-at sq-h1)
        (no-hole-at sq-h2)
        (no-hole-at sq-h3)
        (no-hole-at sq-h4)
        (no-hole-at sq-h5)
        (no-hole-at sq-h6)
        (no-hole-at sq-h7)
        (no-hole-at sq-h8)

        (player-at p1 sq-d5)
        (bomb-at sq-d5)
        (has-no-trampoline)

        (= (time) 0)
        (= (bombs-available p1) 0)
        (= (pliers-available p1) 1)
    )

    (:goal
        (and
            (collected-box b1)
            (collected-box b2)
            (collected-box b3)
            (collected-box b4)
        )
    )

    ;un-comment the following line if metric is needed
    (:metric minimize (time))
)