; with tools
; 282 steps
(define (problem problem_28)
    (:domain sokoban)
    (:objects
        sq-a1 sq-a2 sq-a3 sq-a4 sq-a5 sq-a6 sq-a7 sq-a8 sq-a9 sq-a10 sq-a11 sq-a12 sq-a13 sq-a14 sq-a15 sq-a16 sq-a17 - square
        sq-b1 sq-b2 sq-b3 sq-b4 sq-b5 sq-b6 sq-b7 sq-b8 sq-b9 sq-b10 sq-b11 sq-b12 sq-b13 sq-b14 sq-b15 sq-b16 sq-b17 - square
        sq-c1 sq-c2 sq-c3 sq-c4 sq-c5 sq-c6 sq-c7 sq-c8 sq-c9 sq-c10 sq-c11 sq-c12 sq-c13 sq-c14 sq-c15 sq-c16 sq-c17 - square
        sq-d1 sq-d2 sq-d3 sq-d4 sq-d5 sq-d6 sq-d7 sq-d8 sq-d9 sq-d10 sq-d11 sq-d12 sq-d13 sq-d14 sq-d15 sq-d16 sq-d17 - square
        sq-e1 sq-e2 sq-e3 sq-e4 sq-e5 sq-e6 sq-e7 sq-e8 sq-e9 sq-e10 sq-e11 sq-e12 sq-e13 sq-e14 sq-e15 sq-e16 sq-e17 - square
        sq-f1 sq-f2 sq-f3 sq-f4 sq-f5 sq-f6 sq-f7 sq-f8 sq-f9 sq-f10 sq-f11 sq-f12 sq-f13 sq-f14 sq-f15 sq-f16 sq-f17 - square
        sq-g1 sq-g2 sq-g3 sq-g4 sq-g5 sq-g6 sq-g7 sq-g8 sq-g9 sq-g10 sq-g11 sq-g12 sq-g13 sq-g14 sq-g15 sq-g16 sq-g17 - square
        sq-h1 sq-h2 sq-h3 sq-h4 sq-h5 sq-h6 sq-h7 sq-h8 sq-h9 sq-h10 sq-h11 sq-h12 sq-h13 sq-h14 sq-h15 sq-h16 sq-h17 - square
        sq-i1 sq-i2 sq-i3 sq-i4 sq-i5 sq-i6 sq-i7 sq-i8 sq-i9 sq-i10 sq-i11 sq-i12 sq-i13 sq-i14 sq-i15 sq-i16 sq-i17 - square
        sq-j1 sq-j2 sq-j3 sq-j4 sq-j5 sq-j6 sq-j7 sq-j8 sq-j9 sq-j10 sq-j11 sq-j12 sq-j13 sq-j14 sq-j15 sq-j16 sq-j17 - square
        sq-k1 sq-k2 sq-k3 sq-k4 sq-k5 sq-k6 sq-k7 sq-k8 sq-k9 sq-k10 sq-k11 sq-k12 sq-k13 sq-k14 sq-k15 sq-k16 sq-k17 - square
        sq-l1 sq-l2 sq-l3 sq-l4 sq-l5 sq-l6 sq-l7 sq-l8 sq-l9 sq-l10 sq-l11 sq-l12 sq-l13 sq-l14 sq-l15 sq-l16 sq-l17 - square
        sq-m1 sq-m2 sq-m3 sq-m4 sq-m5 sq-m6 sq-m7 sq-m8 sq-m9 sq-m10 sq-m11 sq-m12 sq-m13 sq-m14 sq-m15 sq-m16 sq-m17 - square
        sq-n1 sq-n2 sq-n3 sq-n4 sq-n5 sq-n6 sq-n7 sq-n8 sq-n9 sq-n10 sq-n11 sq-n12 sq-n13 sq-n14 sq-n15 sq-n16 sq-n17 - square
        sq-o1 sq-o2 sq-o3 sq-o4 sq-o5 sq-o6 sq-o7 sq-o8 sq-o9 sq-o10 sq-o11 sq-o12 sq-o13 sq-o14 sq-o15 sq-o16 sq-o17 - square
        sq-p1 sq-p2 sq-p3 sq-p4 sq-p5 sq-p6 sq-p7 sq-p8 sq-p9 sq-p10 sq-p11 sq-p12 sq-p13 sq-p14 sq-p15 sq-p16 sq-p17 - square
        sq-q1 sq-q2 sq-q3 sq-q4 sq-q5 sq-q6 sq-q7 sq-q8 sq-q9 sq-q10 sq-q11 sq-q12 sq-q13 sq-q14 sq-q15 sq-q16 sq-q17 - square
        sq-r1 sq-r2 sq-r3 sq-r4 sq-r5 sq-r6 sq-r7 sq-r8 sq-r9 sq-r10 sq-r11 sq-r12 sq-r13 sq-r14 sq-r15 sq-r16 sq-r17 - square
        sq-s1 sq-s2 sq-s3 sq-s4 sq-s5 sq-s6 sq-s7 sq-s8 sq-s9 sq-s10 sq-s11 sq-s12 sq-s13 sq-s14 sq-s15 sq-s16 sq-s17 - square
        sq-t1 sq-t2 sq-t3 sq-t4 sq-t5 sq-t6 sq-t7 sq-t8 sq-t9 sq-t10 sq-t11 sq-t12 sq-t13 sq-t14 sq-t15 sq-t16 sq-t17 - square
        sq-u1 sq-u2 sq-u3 sq-u4 sq-u5 sq-u6 sq-u7 sq-u8 sq-u9 sq-u10 sq-u11 sq-u12 sq-u13 sq-u14 sq-u15 sq-u16 sq-u17 - square
        sq-v1 sq-v2 sq-v3 sq-v4 sq-v5 sq-v6 sq-v7 sq-v8 sq-v9 sq-v10 sq-v11 sq-v12 sq-v13 sq-v14 sq-v15 sq-v16 sq-v17 - square
        sq-w1 sq-w2 sq-w3 sq-w4 sq-w5 sq-w6 sq-w7 sq-w8 sq-w9 sq-w10 sq-w11 sq-w12 sq-w13 sq-w14 sq-w15 sq-w16 sq-w17 - square
        sq-x1 sq-x2 sq-x3 sq-x4 sq-x5 sq-x6 sq-x7 sq-x8 sq-x9 sq-x10 sq-x11 sq-x12 sq-x13 sq-x14 sq-x15 sq-x16 sq-x17 - square
        sq-y1 sq-y2 sq-y3 sq-y4 sq-y5 sq-y6 sq-y7 sq-y8 sq-y9 sq-y10 sq-y11 sq-y12 sq-y13 sq-y14 sq-y15 sq-y16 sq-y17 - square
        sq-z1 sq-z2 sq-z3 sq-z4 sq-z5 sq-z6 sq-z7 sq-z8 sq-z9 sq-z10 sq-z11 sq-z12 sq-z13 sq-z14 sq-z15 sq-z16 sq-z17 - square
        sq-aa1 sq-aa2 sq-aa3 sq-aa4 sq-aa5 sq-aa6 sq-aa7 sq-aa8 sq-aa9 sq-aa10 sq-aa11 sq-aa12 sq-aa13 sq-aa14 sq-aa15 sq-aa16 sq-aa17 - square
        sq-ab1 sq-ab2 sq-ab3 sq-ab4 sq-ab5 sq-ab6 sq-ab7 sq-ab8 sq-ab9 sq-ab10 sq-ab11 sq-ab12 sq-ab13 sq-ab14 sq-ab15 sq-ab16 sq-ab17 - square
        sq-ac1 sq-ac2 sq-ac3 sq-ac4 sq-ac5 sq-ac6 sq-ac7 sq-ac8 sq-ac9 sq-ac10 sq-ac11 sq-ac12 sq-ac13 sq-ac14 sq-ac15 sq-ac16 sq-ac17 - square
        sq-ad1 sq-ad2 sq-ad3 sq-ad4 sq-ad5 sq-ad6 sq-ad7 sq-ad8 sq-ad9 sq-ad10 sq-ad11 sq-ad12 sq-ad13 sq-ad14 sq-ad15 sq-ad16 sq-ad17 - square
        b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11 - box
    )

    (:init

        (above sq-a1 sq-a2)
        (above sq-a2 sq-a3)
        (above sq-a3 sq-a4)
        (above sq-a4 sq-a5)
        (above sq-a5 sq-a6)
        (above sq-a6 sq-a7)
        (above sq-a7 sq-a8)
        (above sq-a8 sq-a9)
        (above sq-a9 sq-a10)
        (above sq-a10 sq-a11)
        (above sq-a11 sq-a12)
        (above sq-a12 sq-a13)
        (above sq-a13 sq-a14)
        (above sq-a14 sq-a15)
        (above sq-a15 sq-a16)
        (above sq-a16 sq-a17)
        (above sq-b1 sq-b2)
        (above sq-b2 sq-b3)
        (above sq-b3 sq-b4)
        (above sq-b4 sq-b5)
        (above sq-b5 sq-b6)
        (above sq-b6 sq-b7)
        (above sq-b7 sq-b8)
        (above sq-b8 sq-b9)
        (above sq-b9 sq-b10)
        (above sq-b10 sq-b11)
        (above sq-b11 sq-b12)
        (above sq-b12 sq-b13)
        (above sq-b13 sq-b14)
        (above sq-b14 sq-b15)
        (above sq-b15 sq-b16)
        (above sq-b16 sq-b17)
        (above sq-c1 sq-c2)
        (above sq-c2 sq-c3)
        (above sq-c3 sq-c4)
        (above sq-c4 sq-c5)
        (above sq-c5 sq-c6)
        (above sq-c6 sq-c7)
        (above sq-c7 sq-c8)
        (above sq-c8 sq-c9)
        (above sq-c9 sq-c10)
        (above sq-c10 sq-c11)
        (above sq-c11 sq-c12)
        (above sq-c12 sq-c13)
        (above sq-c13 sq-c14)
        (above sq-c14 sq-c15)
        (above sq-c15 sq-c16)
        (above sq-c16 sq-c17)
        (above sq-d1 sq-d2)
        (above sq-d2 sq-d3)
        (above sq-d3 sq-d4)
        (above sq-d4 sq-d5)
        (above sq-d5 sq-d6)
        (above sq-d6 sq-d7)
        (above sq-d7 sq-d8)
        (above sq-d8 sq-d9)
        (above sq-d9 sq-d10)
        (above sq-d10 sq-d11)
        (above sq-d11 sq-d12)
        (above sq-d12 sq-d13)
        (above sq-d13 sq-d14)
        (above sq-d14 sq-d15)
        (above sq-d15 sq-d16)
        (above sq-d16 sq-d17)
        (above sq-e1 sq-e2)
        (above sq-e2 sq-e3)
        (above sq-e3 sq-e4)
        (above sq-e4 sq-e5)
        (above sq-e5 sq-e6)
        (above sq-e6 sq-e7)
        (above sq-e7 sq-e8)
        (above sq-e8 sq-e9)
        (above sq-e9 sq-e10)
        (above sq-e10 sq-e11)
        (above sq-e11 sq-e12)
        (above sq-e12 sq-e13)
        (above sq-e13 sq-e14)
        (above sq-e14 sq-e15)
        (above sq-e15 sq-e16)
        (above sq-e16 sq-e17)
        (above sq-f1 sq-f2)
        (above sq-f2 sq-f3)
        (above sq-f3 sq-f4)
        (above sq-f4 sq-f5)
        (above sq-f5 sq-f6)
        (above sq-f6 sq-f7)
        (above sq-f7 sq-f8)
        (above sq-f8 sq-f9)
        (above sq-f9 sq-f10)
        (above sq-f10 sq-f11)
        (above sq-f11 sq-f12)
        (above sq-f12 sq-f13)
        (above sq-f13 sq-f14)
        (above sq-f14 sq-f15)
        (above sq-f15 sq-f16)
        (above sq-f16 sq-f17)
        (above sq-g1 sq-g2)
        (above sq-g2 sq-g3)
        (above sq-g3 sq-g4)
        (above sq-g4 sq-g5)
        (above sq-g5 sq-g6)
        (above sq-g6 sq-g7)
        (above sq-g7 sq-g8)
        (above sq-g8 sq-g9)
        (above sq-g9 sq-g10)
        (above sq-g10 sq-g11)
        (above sq-g11 sq-g12)
        (above sq-g12 sq-g13)
        (above sq-g13 sq-g14)
        (above sq-g14 sq-g15)
        (above sq-g15 sq-g16)
        (above sq-g16 sq-g17)
        (above sq-h1 sq-h2)
        (above sq-h2 sq-h3)
        (above sq-h3 sq-h4)
        (above sq-h4 sq-h5)
        (above sq-h5 sq-h6)
        (above sq-h6 sq-h7)
        (above sq-h7 sq-h8)
        (above sq-h8 sq-h9)
        (above sq-h9 sq-h10)
        (above sq-h10 sq-h11)
        (above sq-h11 sq-h12)
        (above sq-h12 sq-h13)
        (above sq-h13 sq-h14)
        (above sq-h14 sq-h15)
        (above sq-h15 sq-h16)
        (above sq-h16 sq-h17)
        (above sq-i1 sq-i2)
        (above sq-i2 sq-i3)
        (above sq-i3 sq-i4)
        (above sq-i4 sq-i5)
        (above sq-i5 sq-i6)
        (above sq-i6 sq-i7)
        (above sq-i7 sq-i8)
        (above sq-i8 sq-i9)
        (above sq-i9 sq-i10)
        (above sq-i10 sq-i11)
        (above sq-i11 sq-i12)
        (above sq-i12 sq-i13)
        (above sq-i13 sq-i14)
        (above sq-i14 sq-i15)
        (above sq-i15 sq-i16)
        (above sq-i16 sq-i17)
        (above sq-j1 sq-j2)
        (above sq-j2 sq-j3)
        (above sq-j3 sq-j4)
        (above sq-j4 sq-j5)
        (above sq-j5 sq-j6)
        (above sq-j6 sq-j7)
        (above sq-j7 sq-j8)
        (above sq-j8 sq-j9)
        (above sq-j9 sq-j10)
        (above sq-j10 sq-j11)
        (above sq-j11 sq-j12)
        (above sq-j12 sq-j13)
        (above sq-j13 sq-j14)
        (above sq-j14 sq-j15)
        (above sq-j15 sq-j16)
        (above sq-j16 sq-j17)
        (above sq-k1 sq-k2)
        (above sq-k2 sq-k3)
        (above sq-k3 sq-k4)
        (above sq-k4 sq-k5)
        (above sq-k5 sq-k6)
        (above sq-k6 sq-k7)
        (above sq-k7 sq-k8)
        (above sq-k8 sq-k9)
        (above sq-k9 sq-k10)
        (above sq-k10 sq-k11)
        (above sq-k11 sq-k12)
        (above sq-k12 sq-k13)
        (above sq-k13 sq-k14)
        (above sq-k14 sq-k15)
        (above sq-k15 sq-k16)
        (above sq-k16 sq-k17)
        (above sq-l1 sq-l2)
        (above sq-l2 sq-l3)
        (above sq-l3 sq-l4)
        (above sq-l4 sq-l5)
        (above sq-l5 sq-l6)
        (above sq-l6 sq-l7)
        (above sq-l7 sq-l8)
        (above sq-l8 sq-l9)
        (above sq-l9 sq-l10)
        (above sq-l10 sq-l11)
        (above sq-l11 sq-l12)
        (above sq-l12 sq-l13)
        (above sq-l13 sq-l14)
        (above sq-l14 sq-l15)
        (above sq-l15 sq-l16)
        (above sq-l16 sq-l17)
        (above sq-m1 sq-m2)
        (above sq-m2 sq-m3)
        (above sq-m3 sq-m4)
        (above sq-m4 sq-m5)
        (above sq-m5 sq-m6)
        (above sq-m6 sq-m7)
        (above sq-m7 sq-m8)
        (above sq-m8 sq-m9)
        (above sq-m9 sq-m10)
        (above sq-m10 sq-m11)
        (above sq-m11 sq-m12)
        (above sq-m12 sq-m13)
        (above sq-m13 sq-m14)
        (above sq-m14 sq-m15)
        (above sq-m15 sq-m16)
        (above sq-m16 sq-m17)
        (above sq-n1 sq-n2)
        (above sq-n2 sq-n3)
        (above sq-n3 sq-n4)
        (above sq-n4 sq-n5)
        (above sq-n5 sq-n6)
        (above sq-n6 sq-n7)
        (above sq-n7 sq-n8)
        (above sq-n8 sq-n9)
        (above sq-n9 sq-n10)
        (above sq-n10 sq-n11)
        (above sq-n11 sq-n12)
        (above sq-n12 sq-n13)
        (above sq-n13 sq-n14)
        (above sq-n14 sq-n15)
        (above sq-n15 sq-n16)
        (above sq-n16 sq-n17)
        (above sq-o1 sq-o2)
        (above sq-o2 sq-o3)
        (above sq-o3 sq-o4)
        (above sq-o4 sq-o5)
        (above sq-o5 sq-o6)
        (above sq-o6 sq-o7)
        (above sq-o7 sq-o8)
        (above sq-o8 sq-o9)
        (above sq-o9 sq-o10)
        (above sq-o10 sq-o11)
        (above sq-o11 sq-o12)
        (above sq-o12 sq-o13)
        (above sq-o13 sq-o14)
        (above sq-o14 sq-o15)
        (above sq-o15 sq-o16)
        (above sq-o16 sq-o17)
        (above sq-p1 sq-p2)
        (above sq-p2 sq-p3)
        (above sq-p3 sq-p4)
        (above sq-p4 sq-p5)
        (above sq-p5 sq-p6)
        (above sq-p6 sq-p7)
        (above sq-p7 sq-p8)
        (above sq-p8 sq-p9)
        (above sq-p9 sq-p10)
        (above sq-p10 sq-p11)
        (above sq-p11 sq-p12)
        (above sq-p12 sq-p13)
        (above sq-p13 sq-p14)
        (above sq-p14 sq-p15)
        (above sq-p15 sq-p16)
        (above sq-p16 sq-p17)
        (above sq-q1 sq-q2)
        (above sq-q2 sq-q3)
        (above sq-q3 sq-q4)
        (above sq-q4 sq-q5)
        (above sq-q5 sq-q6)
        (above sq-q6 sq-q7)
        (above sq-q7 sq-q8)
        (above sq-q8 sq-q9)
        (above sq-q9 sq-q10)
        (above sq-q10 sq-q11)
        (above sq-q11 sq-q12)
        (above sq-q12 sq-q13)
        (above sq-q13 sq-q14)
        (above sq-q14 sq-q15)
        (above sq-q15 sq-q16)
        (above sq-q16 sq-q17)
        (above sq-r1 sq-r2)
        (above sq-r2 sq-r3)
        (above sq-r3 sq-r4)
        (above sq-r4 sq-r5)
        (above sq-r5 sq-r6)
        (above sq-r6 sq-r7)
        (above sq-r7 sq-r8)
        (above sq-r8 sq-r9)
        (above sq-r9 sq-r10)
        (above sq-r10 sq-r11)
        (above sq-r11 sq-r12)
        (above sq-r12 sq-r13)
        (above sq-r13 sq-r14)
        (above sq-r14 sq-r15)
        (above sq-r15 sq-r16)
        (above sq-r16 sq-r17)
        (above sq-s1 sq-s2)
        (above sq-s2 sq-s3)
        (above sq-s3 sq-s4)
        (above sq-s4 sq-s5)
        (above sq-s5 sq-s6)
        (above sq-s6 sq-s7)
        (above sq-s7 sq-s8)
        (above sq-s8 sq-s9)
        (above sq-s9 sq-s10)
        (above sq-s10 sq-s11)
        (above sq-s11 sq-s12)
        (above sq-s12 sq-s13)
        (above sq-s13 sq-s14)
        (above sq-s14 sq-s15)
        (above sq-s15 sq-s16)
        (above sq-s16 sq-s17)
        (above sq-t1 sq-t2)
        (above sq-t2 sq-t3)
        (above sq-t3 sq-t4)
        (above sq-t4 sq-t5)
        (above sq-t5 sq-t6)
        (above sq-t6 sq-t7)
        (above sq-t7 sq-t8)
        (above sq-t8 sq-t9)
        (above sq-t9 sq-t10)
        (above sq-t10 sq-t11)
        (above sq-t11 sq-t12)
        (above sq-t12 sq-t13)
        (above sq-t13 sq-t14)
        (above sq-t14 sq-t15)
        (above sq-t15 sq-t16)
        (above sq-t16 sq-t17)
        (above sq-u1 sq-u2)
        (above sq-u2 sq-u3)
        (above sq-u3 sq-u4)
        (above sq-u4 sq-u5)
        (above sq-u5 sq-u6)
        (above sq-u6 sq-u7)
        (above sq-u7 sq-u8)
        (above sq-u8 sq-u9)
        (above sq-u9 sq-u10)
        (above sq-u10 sq-u11)
        (above sq-u11 sq-u12)
        (above sq-u12 sq-u13)
        (above sq-u13 sq-u14)
        (above sq-u14 sq-u15)
        (above sq-u15 sq-u16)
        (above sq-u16 sq-u17)
        (above sq-v1 sq-v2)
        (above sq-v2 sq-v3)
        (above sq-v3 sq-v4)
        (above sq-v4 sq-v5)
        (above sq-v5 sq-v6)
        (above sq-v6 sq-v7)
        (above sq-v7 sq-v8)
        (above sq-v8 sq-v9)
        (above sq-v9 sq-v10)
        (above sq-v10 sq-v11)
        (above sq-v11 sq-v12)
        (above sq-v12 sq-v13)
        (above sq-v13 sq-v14)
        (above sq-v14 sq-v15)
        (above sq-v15 sq-v16)
        (above sq-v16 sq-v17)
        (above sq-w1 sq-w2)
        (above sq-w2 sq-w3)
        (above sq-w3 sq-w4)
        (above sq-w4 sq-w5)
        (above sq-w5 sq-w6)
        (above sq-w6 sq-w7)
        (above sq-w7 sq-w8)
        (above sq-w8 sq-w9)
        (above sq-w9 sq-w10)
        (above sq-w10 sq-w11)
        (above sq-w11 sq-w12)
        (above sq-w12 sq-w13)
        (above sq-w13 sq-w14)
        (above sq-w14 sq-w15)
        (above sq-w15 sq-w16)
        (above sq-w16 sq-w17)
        (above sq-x1 sq-x2)
        (above sq-x2 sq-x3)
        (above sq-x3 sq-x4)
        (above sq-x4 sq-x5)
        (above sq-x5 sq-x6)
        (above sq-x6 sq-x7)
        (above sq-x7 sq-x8)
        (above sq-x8 sq-x9)
        (above sq-x9 sq-x10)
        (above sq-x10 sq-x11)
        (above sq-x11 sq-x12)
        (above sq-x12 sq-x13)
        (above sq-x13 sq-x14)
        (above sq-x14 sq-x15)
        (above sq-x15 sq-x16)
        (above sq-x16 sq-x17)
        (above sq-y1 sq-y2)
        (above sq-y2 sq-y3)
        (above sq-y3 sq-y4)
        (above sq-y4 sq-y5)
        (above sq-y5 sq-y6)
        (above sq-y6 sq-y7)
        (above sq-y7 sq-y8)
        (above sq-y8 sq-y9)
        (above sq-y9 sq-y10)
        (above sq-y10 sq-y11)
        (above sq-y11 sq-y12)
        (above sq-y12 sq-y13)
        (above sq-y13 sq-y14)
        (above sq-y14 sq-y15)
        (above sq-y15 sq-y16)
        (above sq-y16 sq-y17)
        (above sq-z1 sq-z2)
        (above sq-z2 sq-z3)
        (above sq-z3 sq-z4)
        (above sq-z4 sq-z5)
        (above sq-z5 sq-z6)
        (above sq-z6 sq-z7)
        (above sq-z7 sq-z8)
        (above sq-z8 sq-z9)
        (above sq-z9 sq-z10)
        (above sq-z10 sq-z11)
        (above sq-z11 sq-z12)
        (above sq-z12 sq-z13)
        (above sq-z13 sq-z14)
        (above sq-z14 sq-z15)
        (above sq-z15 sq-z16)
        (above sq-z16 sq-z17)
        (above sq-aa1 sq-aa2)
        (above sq-aa2 sq-aa3)
        (above sq-aa3 sq-aa4)
        (above sq-aa4 sq-aa5)
        (above sq-aa5 sq-aa6)
        (above sq-aa6 sq-aa7)
        (above sq-aa7 sq-aa8)
        (above sq-aa8 sq-aa9)
        (above sq-aa9 sq-aa10)
        (above sq-aa10 sq-aa11)
        (above sq-aa11 sq-aa12)
        (above sq-aa12 sq-aa13)
        (above sq-aa13 sq-aa14)
        (above sq-aa14 sq-aa15)
        (above sq-aa15 sq-aa16)
        (above sq-aa16 sq-aa17)
        (above sq-ab1 sq-ab2)
        (above sq-ab2 sq-ab3)
        (above sq-ab3 sq-ab4)
        (above sq-ab4 sq-ab5)
        (above sq-ab5 sq-ab6)
        (above sq-ab6 sq-ab7)
        (above sq-ab7 sq-ab8)
        (above sq-ab8 sq-ab9)
        (above sq-ab9 sq-ab10)
        (above sq-ab10 sq-ab11)
        (above sq-ab11 sq-ab12)
        (above sq-ab12 sq-ab13)
        (above sq-ab13 sq-ab14)
        (above sq-ab14 sq-ab15)
        (above sq-ab15 sq-ab16)
        (above sq-ab16 sq-ab17)
        (above sq-ac1 sq-ac2)
        (above sq-ac2 sq-ac3)
        (above sq-ac3 sq-ac4)
        (above sq-ac4 sq-ac5)
        (above sq-ac5 sq-ac6)
        (above sq-ac6 sq-ac7)
        (above sq-ac7 sq-ac8)
        (above sq-ac8 sq-ac9)
        (above sq-ac9 sq-ac10)
        (above sq-ac10 sq-ac11)
        (above sq-ac11 sq-ac12)
        (above sq-ac12 sq-ac13)
        (above sq-ac13 sq-ac14)
        (above sq-ac14 sq-ac15)
        (above sq-ac15 sq-ac16)
        (above sq-ac16 sq-ac17)
        (above sq-ad1 sq-ad2)
        (above sq-ad2 sq-ad3)
        (above sq-ad3 sq-ad4)
        (above sq-ad4 sq-ad5)
        (above sq-ad5 sq-ad6)
        (above sq-ad6 sq-ad7)
        (above sq-ad7 sq-ad8)
        (above sq-ad8 sq-ad9)
        (above sq-ad9 sq-ad10)
        (above sq-ad10 sq-ad11)
        (above sq-ad11 sq-ad12)
        (above sq-ad12 sq-ad13)
        (above sq-ad13 sq-ad14)
        (above sq-ad14 sq-ad15)
        (above sq-ad15 sq-ad16)
        (above sq-ad16 sq-ad17)

        (left-to sq-a1 sq-b1)
        (left-to sq-a2 sq-b2)
        (left-to sq-a3 sq-b3)
        (left-to sq-a4 sq-b4)
        (left-to sq-a5 sq-b5)
        (left-to sq-a6 sq-b6)
        (left-to sq-a7 sq-b7)
        (left-to sq-a8 sq-b8)
        (left-to sq-a9 sq-b9)
        (left-to sq-a10 sq-b10)
        (left-to sq-a11 sq-b11)
        (left-to sq-a12 sq-b12)
        (left-to sq-a13 sq-b13)
        (left-to sq-a14 sq-b14)
        (left-to sq-a15 sq-b15)
        (left-to sq-a16 sq-b16)
        (left-to sq-a17 sq-b17)
        (left-to sq-b1 sq-c1)
        (left-to sq-b2 sq-c2)
        (left-to sq-b3 sq-c3)
        (left-to sq-b4 sq-c4)
        (left-to sq-b5 sq-c5)
        (left-to sq-b6 sq-c6)
        (left-to sq-b7 sq-c7)
        (left-to sq-b8 sq-c8)
        (left-to sq-b9 sq-c9)
        (left-to sq-b10 sq-c10)
        (left-to sq-b11 sq-c11)
        (left-to sq-b12 sq-c12)
        (left-to sq-b13 sq-c13)
        (left-to sq-b14 sq-c14)
        (left-to sq-b15 sq-c15)
        (left-to sq-b16 sq-c16)
        (left-to sq-b17 sq-c17)
        (left-to sq-c1 sq-d1)
        (left-to sq-c2 sq-d2)
        (left-to sq-c3 sq-d3)
        (left-to sq-c4 sq-d4)
        (left-to sq-c5 sq-d5)
        (left-to sq-c6 sq-d6)
        (left-to sq-c7 sq-d7)
        (left-to sq-c8 sq-d8)
        (left-to sq-c9 sq-d9)
        (left-to sq-c10 sq-d10)
        (left-to sq-c11 sq-d11)
        (left-to sq-c12 sq-d12)
        (left-to sq-c13 sq-d13)
        (left-to sq-c14 sq-d14)
        (left-to sq-c15 sq-d15)
        (left-to sq-c16 sq-d16)
        (left-to sq-c17 sq-d17)
        (left-to sq-d1 sq-e1)
        (left-to sq-d2 sq-e2)
        (left-to sq-d3 sq-e3)
        (left-to sq-d4 sq-e4)
        (left-to sq-d5 sq-e5)
        (left-to sq-d6 sq-e6)
        (left-to sq-d7 sq-e7)
        (left-to sq-d8 sq-e8)
        (left-to sq-d9 sq-e9)
        (left-to sq-d10 sq-e10)
        (left-to sq-d11 sq-e11)
        (left-to sq-d12 sq-e12)
        (left-to sq-d13 sq-e13)
        (left-to sq-d14 sq-e14)
        (left-to sq-d15 sq-e15)
        (left-to sq-d16 sq-e16)
        (left-to sq-d17 sq-e17)
        (left-to sq-e1 sq-f1)
        (left-to sq-e2 sq-f2)
        (left-to sq-e3 sq-f3)
        (left-to sq-e4 sq-f4)
        (left-to sq-e5 sq-f5)
        (left-to sq-e6 sq-f6)
        (left-to sq-e7 sq-f7)
        (left-to sq-e8 sq-f8)
        (left-to sq-e9 sq-f9)
        (left-to sq-e10 sq-f10)
        (left-to sq-e11 sq-f11)
        (left-to sq-e12 sq-f12)
        (left-to sq-e13 sq-f13)
        (left-to sq-e14 sq-f14)
        (left-to sq-e15 sq-f15)
        (left-to sq-e16 sq-f16)
        (left-to sq-e17 sq-f17)
        (left-to sq-f1 sq-g1)
        (left-to sq-f2 sq-g2)
        (left-to sq-f3 sq-g3)
        (left-to sq-f4 sq-g4)
        (left-to sq-f5 sq-g5)
        (left-to sq-f6 sq-g6)
        (left-to sq-f7 sq-g7)
        (left-to sq-f8 sq-g8)
        (left-to sq-f9 sq-g9)
        (left-to sq-f10 sq-g10)
        (left-to sq-f11 sq-g11)
        (left-to sq-f12 sq-g12)
        (left-to sq-f13 sq-g13)
        (left-to sq-f14 sq-g14)
        (left-to sq-f15 sq-g15)
        (left-to sq-f16 sq-g16)
        (left-to sq-f17 sq-g17)
        (left-to sq-g1 sq-h1)
        (left-to sq-g2 sq-h2)
        (left-to sq-g3 sq-h3)
        (left-to sq-g4 sq-h4)
        (left-to sq-g5 sq-h5)
        (left-to sq-g6 sq-h6)
        (left-to sq-g7 sq-h7)
        (left-to sq-g8 sq-h8)
        (left-to sq-g9 sq-h9)
        (left-to sq-g10 sq-h10)
        (left-to sq-g11 sq-h11)
        (left-to sq-g12 sq-h12)
        (left-to sq-g13 sq-h13)
        (left-to sq-g14 sq-h14)
        (left-to sq-g15 sq-h15)
        (left-to sq-g16 sq-h16)
        (left-to sq-g17 sq-h17)
        (left-to sq-h1 sq-i1)
        (left-to sq-h2 sq-i2)
        (left-to sq-h3 sq-i3)
        (left-to sq-h4 sq-i4)
        (left-to sq-h5 sq-i5)
        (left-to sq-h6 sq-i6)
        (left-to sq-h7 sq-i7)
        (left-to sq-h8 sq-i8)
        (left-to sq-h9 sq-i9)
        (left-to sq-h10 sq-i10)
        (left-to sq-h11 sq-i11)
        (left-to sq-h12 sq-i12)
        (left-to sq-h13 sq-i13)
        (left-to sq-h14 sq-i14)
        (left-to sq-h15 sq-i15)
        (left-to sq-h16 sq-i16)
        (left-to sq-h17 sq-i17)
        (left-to sq-i1 sq-j1)
        (left-to sq-i2 sq-j2)
        (left-to sq-i3 sq-j3)
        (left-to sq-i4 sq-j4)
        (left-to sq-i5 sq-j5)
        (left-to sq-i6 sq-j6)
        (left-to sq-i7 sq-j7)
        (left-to sq-i8 sq-j8)
        (left-to sq-i9 sq-j9)
        (left-to sq-i10 sq-j10)
        (left-to sq-i11 sq-j11)
        (left-to sq-i12 sq-j12)
        (left-to sq-i13 sq-j13)
        (left-to sq-i14 sq-j14)
        (left-to sq-i15 sq-j15)
        (left-to sq-i16 sq-j16)
        (left-to sq-i17 sq-j17)
        (left-to sq-j1 sq-k1)
        (left-to sq-j2 sq-k2)
        (left-to sq-j3 sq-k3)
        (left-to sq-j4 sq-k4)
        (left-to sq-j5 sq-k5)
        (left-to sq-j6 sq-k6)
        (left-to sq-j7 sq-k7)
        (left-to sq-j8 sq-k8)
        (left-to sq-j9 sq-k9)
        (left-to sq-j10 sq-k10)
        (left-to sq-j11 sq-k11)
        (left-to sq-j12 sq-k12)
        (left-to sq-j13 sq-k13)
        (left-to sq-j14 sq-k14)
        (left-to sq-j15 sq-k15)
        (left-to sq-j16 sq-k16)
        (left-to sq-j17 sq-k17)
        (left-to sq-k1 sq-l1)
        (left-to sq-k2 sq-l2)
        (left-to sq-k3 sq-l3)
        (left-to sq-k4 sq-l4)
        (left-to sq-k5 sq-l5)
        (left-to sq-k6 sq-l6)
        (left-to sq-k7 sq-l7)
        (left-to sq-k8 sq-l8)
        (left-to sq-k9 sq-l9)
        (left-to sq-k10 sq-l10)
        (left-to sq-k11 sq-l11)
        (left-to sq-k12 sq-l12)
        (left-to sq-k13 sq-l13)
        (left-to sq-k14 sq-l14)
        (left-to sq-k15 sq-l15)
        (left-to sq-k16 sq-l16)
        (left-to sq-k17 sq-l17)
        (left-to sq-l1 sq-m1)
        (left-to sq-l2 sq-m2)
        (left-to sq-l3 sq-m3)
        (left-to sq-l4 sq-m4)
        (left-to sq-l5 sq-m5)
        (left-to sq-l6 sq-m6)
        (left-to sq-l7 sq-m7)
        (left-to sq-l8 sq-m8)
        (left-to sq-l9 sq-m9)
        (left-to sq-l10 sq-m10)
        (left-to sq-l11 sq-m11)
        (left-to sq-l12 sq-m12)
        (left-to sq-l13 sq-m13)
        (left-to sq-l14 sq-m14)
        (left-to sq-l15 sq-m15)
        (left-to sq-l16 sq-m16)
        (left-to sq-l17 sq-m17)
        (left-to sq-m1 sq-n1)
        (left-to sq-m2 sq-n2)
        (left-to sq-m3 sq-n3)
        (left-to sq-m4 sq-n4)
        (left-to sq-m5 sq-n5)
        (left-to sq-m6 sq-n6)
        (left-to sq-m7 sq-n7)
        (left-to sq-m8 sq-n8)
        (left-to sq-m9 sq-n9)
        (left-to sq-m10 sq-n10)
        (left-to sq-m11 sq-n11)
        (left-to sq-m12 sq-n12)
        (left-to sq-m13 sq-n13)
        (left-to sq-m14 sq-n14)
        (left-to sq-m15 sq-n15)
        (left-to sq-m16 sq-n16)
        (left-to sq-m17 sq-n17)
        (left-to sq-n1 sq-o1)
        (left-to sq-n2 sq-o2)
        (left-to sq-n3 sq-o3)
        (left-to sq-n4 sq-o4)
        (left-to sq-n5 sq-o5)
        (left-to sq-n6 sq-o6)
        (left-to sq-n7 sq-o7)
        (left-to sq-n8 sq-o8)
        (left-to sq-n9 sq-o9)
        (left-to sq-n10 sq-o10)
        (left-to sq-n11 sq-o11)
        (left-to sq-n12 sq-o12)
        (left-to sq-n13 sq-o13)
        (left-to sq-n14 sq-o14)
        (left-to sq-n15 sq-o15)
        (left-to sq-n16 sq-o16)
        (left-to sq-n17 sq-o17)
        (left-to sq-o1 sq-p1)
        (left-to sq-o2 sq-p2)
        (left-to sq-o3 sq-p3)
        (left-to sq-o4 sq-p4)
        (left-to sq-o5 sq-p5)
        (left-to sq-o6 sq-p6)
        (left-to sq-o7 sq-p7)
        (left-to sq-o8 sq-p8)
        (left-to sq-o9 sq-p9)
        (left-to sq-o10 sq-p10)
        (left-to sq-o11 sq-p11)
        (left-to sq-o12 sq-p12)
        (left-to sq-o13 sq-p13)
        (left-to sq-o14 sq-p14)
        (left-to sq-o15 sq-p15)
        (left-to sq-o16 sq-p16)
        (left-to sq-o17 sq-p17)
        (left-to sq-p1 sq-q1)
        (left-to sq-p2 sq-q2)
        (left-to sq-p3 sq-q3)
        (left-to sq-p4 sq-q4)
        (left-to sq-p5 sq-q5)
        (left-to sq-p6 sq-q6)
        (left-to sq-p7 sq-q7)
        (left-to sq-p8 sq-q8)
        (left-to sq-p9 sq-q9)
        (left-to sq-p10 sq-q10)
        (left-to sq-p11 sq-q11)
        (left-to sq-p12 sq-q12)
        (left-to sq-p13 sq-q13)
        (left-to sq-p14 sq-q14)
        (left-to sq-p15 sq-q15)
        (left-to sq-p16 sq-q16)
        (left-to sq-p17 sq-q17)
        (left-to sq-q1 sq-r1)
        (left-to sq-q2 sq-r2)
        (left-to sq-q3 sq-r3)
        (left-to sq-q4 sq-r4)
        (left-to sq-q5 sq-r5)
        (left-to sq-q6 sq-r6)
        (left-to sq-q7 sq-r7)
        (left-to sq-q8 sq-r8)
        (left-to sq-q9 sq-r9)
        (left-to sq-q10 sq-r10)
        (left-to sq-q11 sq-r11)
        (left-to sq-q12 sq-r12)
        (left-to sq-q13 sq-r13)
        (left-to sq-q14 sq-r14)
        (left-to sq-q15 sq-r15)
        (left-to sq-q16 sq-r16)
        (left-to sq-q17 sq-r17)
        (left-to sq-r1 sq-s1)
        (left-to sq-r2 sq-s2)
        (left-to sq-r3 sq-s3)
        (left-to sq-r4 sq-s4)
        (left-to sq-r5 sq-s5)
        (left-to sq-r6 sq-s6)
        (left-to sq-r7 sq-s7)
        (left-to sq-r8 sq-s8)
        (left-to sq-r9 sq-s9)
        (left-to sq-r10 sq-s10)
        (left-to sq-r11 sq-s11)
        (left-to sq-r12 sq-s12)
        (left-to sq-r13 sq-s13)
        (left-to sq-r14 sq-s14)
        (left-to sq-r15 sq-s15)
        (left-to sq-r16 sq-s16)
        (left-to sq-r17 sq-s17)
        (left-to sq-s1 sq-t1)
        (left-to sq-s2 sq-t2)
        (left-to sq-s3 sq-t3)
        (left-to sq-s4 sq-t4)
        (left-to sq-s5 sq-t5)
        (left-to sq-s6 sq-t6)
        (left-to sq-s7 sq-t7)
        (left-to sq-s8 sq-t8)
        (left-to sq-s9 sq-t9)
        (left-to sq-s10 sq-t10)
        (left-to sq-s11 sq-t11)
        (left-to sq-s12 sq-t12)
        (left-to sq-s13 sq-t13)
        (left-to sq-s14 sq-t14)
        (left-to sq-s15 sq-t15)
        (left-to sq-s16 sq-t16)
        (left-to sq-s17 sq-t17)
        (left-to sq-t1 sq-u1)
        (left-to sq-t2 sq-u2)
        (left-to sq-t3 sq-u3)
        (left-to sq-t4 sq-u4)
        (left-to sq-t5 sq-u5)
        (left-to sq-t6 sq-u6)
        (left-to sq-t7 sq-u7)
        (left-to sq-t8 sq-u8)
        (left-to sq-t9 sq-u9)
        (left-to sq-t10 sq-u10)
        (left-to sq-t11 sq-u11)
        (left-to sq-t12 sq-u12)
        (left-to sq-t13 sq-u13)
        (left-to sq-t14 sq-u14)
        (left-to sq-t15 sq-u15)
        (left-to sq-t16 sq-u16)
        (left-to sq-t17 sq-u17)
        (left-to sq-u1 sq-v1)
        (left-to sq-u2 sq-v2)
        (left-to sq-u3 sq-v3)
        (left-to sq-u4 sq-v4)
        (left-to sq-u5 sq-v5)
        (left-to sq-u6 sq-v6)
        (left-to sq-u7 sq-v7)
        (left-to sq-u8 sq-v8)
        (left-to sq-u9 sq-v9)
        (left-to sq-u10 sq-v10)
        (left-to sq-u11 sq-v11)
        (left-to sq-u12 sq-v12)
        (left-to sq-u13 sq-v13)
        (left-to sq-u14 sq-v14)
        (left-to sq-u15 sq-v15)
        (left-to sq-u16 sq-v16)
        (left-to sq-u17 sq-v17)
        (left-to sq-v1 sq-w1)
        (left-to sq-v2 sq-w2)
        (left-to sq-v3 sq-w3)
        (left-to sq-v4 sq-w4)
        (left-to sq-v5 sq-w5)
        (left-to sq-v6 sq-w6)
        (left-to sq-v7 sq-w7)
        (left-to sq-v8 sq-w8)
        (left-to sq-v9 sq-w9)
        (left-to sq-v10 sq-w10)
        (left-to sq-v11 sq-w11)
        (left-to sq-v12 sq-w12)
        (left-to sq-v13 sq-w13)
        (left-to sq-v14 sq-w14)
        (left-to sq-v15 sq-w15)
        (left-to sq-v16 sq-w16)
        (left-to sq-v17 sq-w17)
        (left-to sq-w1 sq-x1)
        (left-to sq-w2 sq-x2)
        (left-to sq-w3 sq-x3)
        (left-to sq-w4 sq-x4)
        (left-to sq-w5 sq-x5)
        (left-to sq-w6 sq-x6)
        (left-to sq-w7 sq-x7)
        (left-to sq-w8 sq-x8)
        (left-to sq-w9 sq-x9)
        (left-to sq-w10 sq-x10)
        (left-to sq-w11 sq-x11)
        (left-to sq-w12 sq-x12)
        (left-to sq-w13 sq-x13)
        (left-to sq-w14 sq-x14)
        (left-to sq-w15 sq-x15)
        (left-to sq-w16 sq-x16)
        (left-to sq-w17 sq-x17)
        (left-to sq-x1 sq-y1)
        (left-to sq-x2 sq-y2)
        (left-to sq-x3 sq-y3)
        (left-to sq-x4 sq-y4)
        (left-to sq-x5 sq-y5)
        (left-to sq-x6 sq-y6)
        (left-to sq-x7 sq-y7)
        (left-to sq-x8 sq-y8)
        (left-to sq-x9 sq-y9)
        (left-to sq-x10 sq-y10)
        (left-to sq-x11 sq-y11)
        (left-to sq-x12 sq-y12)
        (left-to sq-x13 sq-y13)
        (left-to sq-x14 sq-y14)
        (left-to sq-x15 sq-y15)
        (left-to sq-x16 sq-y16)
        (left-to sq-x17 sq-y17)
        (left-to sq-y1 sq-z1)
        (left-to sq-y2 sq-z2)
        (left-to sq-y3 sq-z3)
        (left-to sq-y4 sq-z4)
        (left-to sq-y5 sq-z5)
        (left-to sq-y6 sq-z6)
        (left-to sq-y7 sq-z7)
        (left-to sq-y8 sq-z8)
        (left-to sq-y9 sq-z9)
        (left-to sq-y10 sq-z10)
        (left-to sq-y11 sq-z11)
        (left-to sq-y12 sq-z12)
        (left-to sq-y13 sq-z13)
        (left-to sq-y14 sq-z14)
        (left-to sq-y15 sq-z15)
        (left-to sq-y16 sq-z16)
        (left-to sq-y17 sq-z17)
        (left-to sq-z1 sq-aa1)
        (left-to sq-z2 sq-aa2)
        (left-to sq-z3 sq-aa3)
        (left-to sq-z4 sq-aa4)
        (left-to sq-z5 sq-aa5)
        (left-to sq-z6 sq-aa6)
        (left-to sq-z7 sq-aa7)
        (left-to sq-z8 sq-aa8)
        (left-to sq-z9 sq-aa9)
        (left-to sq-z10 sq-aa10)
        (left-to sq-z11 sq-aa11)
        (left-to sq-z12 sq-aa12)
        (left-to sq-z13 sq-aa13)
        (left-to sq-z14 sq-aa14)
        (left-to sq-z15 sq-aa15)
        (left-to sq-z16 sq-aa16)
        (left-to sq-z17 sq-aa17)
        (left-to sq-aa1 sq-ab1)
        (left-to sq-aa2 sq-ab2)
        (left-to sq-aa3 sq-ab3)
        (left-to sq-aa4 sq-ab4)
        (left-to sq-aa5 sq-ab5)
        (left-to sq-aa6 sq-ab6)
        (left-to sq-aa7 sq-ab7)
        (left-to sq-aa8 sq-ab8)
        (left-to sq-aa9 sq-ab9)
        (left-to sq-aa10 sq-ab10)
        (left-to sq-aa11 sq-ab11)
        (left-to sq-aa12 sq-ab12)
        (left-to sq-aa13 sq-ab13)
        (left-to sq-aa14 sq-ab14)
        (left-to sq-aa15 sq-ab15)
        (left-to sq-aa16 sq-ab16)
        (left-to sq-aa17 sq-ab17)
        (left-to sq-ab1 sq-ac1)
        (left-to sq-ab2 sq-ac2)
        (left-to sq-ab3 sq-ac3)
        (left-to sq-ab4 sq-ac4)
        (left-to sq-ab5 sq-ac5)
        (left-to sq-ab6 sq-ac6)
        (left-to sq-ab7 sq-ac7)
        (left-to sq-ab8 sq-ac8)
        (left-to sq-ab9 sq-ac9)
        (left-to sq-ab10 sq-ac10)
        (left-to sq-ab11 sq-ac11)
        (left-to sq-ab12 sq-ac12)
        (left-to sq-ab13 sq-ac13)
        (left-to sq-ab14 sq-ac14)
        (left-to sq-ab15 sq-ac15)
        (left-to sq-ab16 sq-ac16)
        (left-to sq-ab17 sq-ac17)
        (left-to sq-ac1 sq-ad1)
        (left-to sq-ac2 sq-ad2)
        (left-to sq-ac3 sq-ad3)
        (left-to sq-ac4 sq-ad4)
        (left-to sq-ac5 sq-ad5)
        (left-to sq-ac6 sq-ad6)
        (left-to sq-ac7 sq-ad7)
        (left-to sq-ac8 sq-ad8)
        (left-to sq-ac9 sq-ad9)
        (left-to sq-ac10 sq-ad10)
        (left-to sq-ac11 sq-ad11)
        (left-to sq-ac12 sq-ad12)
        (left-to sq-ac13 sq-ad13)
        (left-to sq-ac14 sq-ad14)
        (left-to sq-ac15 sq-ad15)
        (left-to sq-ac16 sq-ad16)
        (left-to sq-ac17 sq-ad17)

        (box-at b1 sq-b6)
        (box-at b2 sq-b7)
        (box-at b3 sq-f2)
        (box-at b4 sq-i9)
        (box-at b5 sq-k12)
        (box-at b6 sq-k13)
        (box-at b7 sq-l12)
        (box-at b8 sq-l13)
        (box-at b9 sq-s15)
        (box-at b10 sq-ac15)
        (box-at b11 sq-ac16)

        (hole-at sq-b6)
        (hole-at sq-b7)
        (hole-at sq-f2)
        (hole-at sq-g6)
        (hole-at sq-i9)
        (hole-at sq-k12)
        (hole-at sq-k13)
        (hole-at sq-l12)
        (hole-at sq-l13)
        (hole-at sq-ac15)
        (hole-at sq-ac16)

        (no-hole-at sq-a1)
        (no-hole-at sq-a2)
        (no-hole-at sq-a3)
        (no-hole-at sq-a4)
        (no-hole-at sq-a5)
        (no-hole-at sq-a6)
        (no-hole-at sq-a7)
        (no-hole-at sq-a8)
        (no-hole-at sq-a9)
        (no-hole-at sq-a10)
        (no-hole-at sq-a11)
        (no-hole-at sq-a12)
        (no-hole-at sq-a13)
        (no-hole-at sq-a14)
        (no-hole-at sq-a15)
        (no-hole-at sq-a16)
        (no-hole-at sq-a17)
        (no-hole-at sq-b1)
        (no-hole-at sq-b2)
        (no-hole-at sq-b3)
        (no-hole-at sq-b4)
        (no-hole-at sq-b5)
        (no-hole-at sq-b8)
        (no-hole-at sq-b9)
        (no-hole-at sq-b10)
        (no-hole-at sq-b11)
        (no-hole-at sq-b12)
        (no-hole-at sq-b13)
        (no-hole-at sq-b14)
        (no-hole-at sq-b15)
        (no-hole-at sq-b16)
        (no-hole-at sq-b17)
        (no-hole-at sq-c1)
        (no-hole-at sq-c2)
        (no-hole-at sq-c3)
        (no-hole-at sq-c4)
        (no-hole-at sq-c5)
        (no-hole-at sq-c6)
        (no-hole-at sq-c7)
        (no-hole-at sq-c8)
        (no-hole-at sq-c9)
        (no-hole-at sq-c10)
        (no-hole-at sq-c11)
        (no-hole-at sq-c12)
        (no-hole-at sq-c13)
        (no-hole-at sq-c14)
        (no-hole-at sq-c15)
        (no-hole-at sq-c16)
        (no-hole-at sq-c17)
        (no-hole-at sq-d1)
        (no-hole-at sq-d2)
        (no-hole-at sq-d3)
        (no-hole-at sq-d4)
        (no-hole-at sq-d5)
        (no-hole-at sq-d6)
        (no-hole-at sq-d7)
        (no-hole-at sq-d8)
        (no-hole-at sq-d9)
        (no-hole-at sq-d10)
        (no-hole-at sq-d11)
        (no-hole-at sq-d12)
        (no-hole-at sq-d13)
        (no-hole-at sq-d14)
        (no-hole-at sq-d15)
        (no-hole-at sq-d16)
        (no-hole-at sq-d17)
        (no-hole-at sq-e1)
        (no-hole-at sq-e2)
        (no-hole-at sq-e3)
        (no-hole-at sq-e4)
        (no-hole-at sq-e5)
        (no-hole-at sq-e6)
        (no-hole-at sq-e7)
        (no-hole-at sq-e8)
        (no-hole-at sq-e9)
        (no-hole-at sq-e10)
        (no-hole-at sq-e11)
        (no-hole-at sq-e12)
        (no-hole-at sq-e13)
        (no-hole-at sq-e14)
        (no-hole-at sq-e15)
        (no-hole-at sq-e16)
        (no-hole-at sq-e17)
        (no-hole-at sq-f1)
        (no-hole-at sq-f3)
        (no-hole-at sq-f4)
        (no-hole-at sq-f5)
        (no-hole-at sq-f6)
        (no-hole-at sq-f7)
        (no-hole-at sq-f8)
        (no-hole-at sq-f9)
        (no-hole-at sq-f10)
        (no-hole-at sq-f11)
        (no-hole-at sq-f12)
        (no-hole-at sq-f13)
        (no-hole-at sq-f14)
        (no-hole-at sq-f15)
        (no-hole-at sq-f16)
        (no-hole-at sq-f17)
        (no-hole-at sq-g1)
        (no-hole-at sq-g2)
        (no-hole-at sq-g3)
        (no-hole-at sq-g4)
        (no-hole-at sq-g5)
        (no-hole-at sq-g7)
        (no-hole-at sq-g8)
        (no-hole-at sq-g9)
        (no-hole-at sq-g10)
        (no-hole-at sq-g11)
        (no-hole-at sq-g12)
        (no-hole-at sq-g13)
        (no-hole-at sq-g14)
        (no-hole-at sq-g15)
        (no-hole-at sq-g16)
        (no-hole-at sq-g17)
        (no-hole-at sq-h1)
        (no-hole-at sq-h2)
        (no-hole-at sq-h3)
        (no-hole-at sq-h4)
        (no-hole-at sq-h5)
        (no-hole-at sq-h6)
        (no-hole-at sq-h7)
        (no-hole-at sq-h8)
        (no-hole-at sq-h9)
        (no-hole-at sq-h10)
        (no-hole-at sq-h11)
        (no-hole-at sq-h12)
        (no-hole-at sq-h13)
        (no-hole-at sq-h14)
        (no-hole-at sq-h15)
        (no-hole-at sq-h16)
        (no-hole-at sq-h17)
        (no-hole-at sq-i1)
        (no-hole-at sq-i2)
        (no-hole-at sq-i3)
        (no-hole-at sq-i4)
        (no-hole-at sq-i5)
        (no-hole-at sq-i6)
        (no-hole-at sq-i7)
        (no-hole-at sq-i8)
        (no-hole-at sq-i10)
        (no-hole-at sq-i11)
        (no-hole-at sq-i12)
        (no-hole-at sq-i13)
        (no-hole-at sq-i14)
        (no-hole-at sq-i15)
        (no-hole-at sq-i16)
        (no-hole-at sq-i17)
        (no-hole-at sq-j1)
        (no-hole-at sq-j2)
        (no-hole-at sq-j3)
        (no-hole-at sq-j4)
        (no-hole-at sq-j5)
        (no-hole-at sq-j6)
        (no-hole-at sq-j7)
        (no-hole-at sq-j8)
        (no-hole-at sq-j9)
        (no-hole-at sq-j10)
        (no-hole-at sq-j11)
        (no-hole-at sq-j12)
        (no-hole-at sq-j13)
        (no-hole-at sq-j14)
        (no-hole-at sq-j15)
        (no-hole-at sq-j16)
        (no-hole-at sq-j17)
        (no-hole-at sq-k1)
        (no-hole-at sq-k2)
        (no-hole-at sq-k3)
        (no-hole-at sq-k4)
        (no-hole-at sq-k5)
        (no-hole-at sq-k6)
        (no-hole-at sq-k7)
        (no-hole-at sq-k8)
        (no-hole-at sq-k9)
        (no-hole-at sq-k10)
        (no-hole-at sq-k11)
        (no-hole-at sq-k14)
        (no-hole-at sq-k15)
        (no-hole-at sq-k16)
        (no-hole-at sq-k17)
        (no-hole-at sq-l1)
        (no-hole-at sq-l2)
        (no-hole-at sq-l3)
        (no-hole-at sq-l4)
        (no-hole-at sq-l5)
        (no-hole-at sq-l6)
        (no-hole-at sq-l7)
        (no-hole-at sq-l8)
        (no-hole-at sq-l9)
        (no-hole-at sq-l10)
        (no-hole-at sq-l11)
        (no-hole-at sq-l14)
        (no-hole-at sq-l15)
        (no-hole-at sq-l16)
        (no-hole-at sq-l17)
        (no-hole-at sq-m1)
        (no-hole-at sq-m2)
        (no-hole-at sq-m3)
        (no-hole-at sq-m4)
        (no-hole-at sq-m5)
        (no-hole-at sq-m6)
        (no-hole-at sq-m7)
        (no-hole-at sq-m8)
        (no-hole-at sq-m9)
        (no-hole-at sq-m10)
        (no-hole-at sq-m11)
        (no-hole-at sq-m12)
        (no-hole-at sq-m13)
        (no-hole-at sq-m14)
        (no-hole-at sq-m15)
        (no-hole-at sq-m16)
        (no-hole-at sq-m17)
        (no-hole-at sq-n1)
        (no-hole-at sq-n2)
        (no-hole-at sq-n3)
        (no-hole-at sq-n4)
        (no-hole-at sq-n5)
        (no-hole-at sq-n6)
        (no-hole-at sq-n7)
        (no-hole-at sq-n8)
        (no-hole-at sq-n9)
        (no-hole-at sq-n10)
        (no-hole-at sq-n11)
        (no-hole-at sq-n12)
        (no-hole-at sq-n13)
        (no-hole-at sq-n14)
        (no-hole-at sq-n15)
        (no-hole-at sq-n16)
        (no-hole-at sq-n17)
        (no-hole-at sq-o1)
        (no-hole-at sq-o2)
        (no-hole-at sq-o3)
        (no-hole-at sq-o4)
        (no-hole-at sq-o5)
        (no-hole-at sq-o6)
        (no-hole-at sq-o7)
        (no-hole-at sq-o8)
        (no-hole-at sq-o9)
        (no-hole-at sq-o10)
        (no-hole-at sq-o11)
        (no-hole-at sq-o12)
        (no-hole-at sq-o13)
        (no-hole-at sq-o14)
        (no-hole-at sq-o15)
        (no-hole-at sq-o16)
        (no-hole-at sq-o17)
        (no-hole-at sq-p1)
        (no-hole-at sq-p2)
        (no-hole-at sq-p3)
        (no-hole-at sq-p4)
        (no-hole-at sq-p5)
        (no-hole-at sq-p6)
        (no-hole-at sq-p7)
        (no-hole-at sq-p8)
        (no-hole-at sq-p9)
        (no-hole-at sq-p10)
        (no-hole-at sq-p11)
        (no-hole-at sq-p12)
        (no-hole-at sq-p13)
        (no-hole-at sq-p14)
        (no-hole-at sq-p15)
        (no-hole-at sq-p16)
        (no-hole-at sq-p17)
        (no-hole-at sq-q1)
        (no-hole-at sq-q2)
        (no-hole-at sq-q3)
        (no-hole-at sq-q4)
        (no-hole-at sq-q5)
        (no-hole-at sq-q6)
        (no-hole-at sq-q7)
        (no-hole-at sq-q8)
        (no-hole-at sq-q9)
        (no-hole-at sq-q10)
        (no-hole-at sq-q11)
        (no-hole-at sq-q12)
        (no-hole-at sq-q13)
        (no-hole-at sq-q14)
        (no-hole-at sq-q15)
        (no-hole-at sq-q16)
        (no-hole-at sq-q17)
        (no-hole-at sq-r1)
        (no-hole-at sq-r2)
        (no-hole-at sq-r3)
        (no-hole-at sq-r4)
        (no-hole-at sq-r5)
        (no-hole-at sq-r6)
        (no-hole-at sq-r7)
        (no-hole-at sq-r8)
        (no-hole-at sq-r9)
        (no-hole-at sq-r10)
        (no-hole-at sq-r11)
        (no-hole-at sq-r12)
        (no-hole-at sq-r13)
        (no-hole-at sq-r14)
        (no-hole-at sq-r15)
        (no-hole-at sq-r16)
        (no-hole-at sq-r17)
        (no-hole-at sq-s1)
        (no-hole-at sq-s2)
        (no-hole-at sq-s3)
        (no-hole-at sq-s4)
        (no-hole-at sq-s5)
        (no-hole-at sq-s6)
        (no-hole-at sq-s7)
        (no-hole-at sq-s8)
        (no-hole-at sq-s9)
        (no-hole-at sq-s10)
        (no-hole-at sq-s11)
        (no-hole-at sq-s12)
        (no-hole-at sq-s13)
        (no-hole-at sq-s14)
        (no-hole-at sq-s15)
        (no-hole-at sq-s16)
        (no-hole-at sq-s17)
        (no-hole-at sq-t1)
        (no-hole-at sq-t2)
        (no-hole-at sq-t3)
        (no-hole-at sq-t4)
        (no-hole-at sq-t5)
        (no-hole-at sq-t6)
        (no-hole-at sq-t7)
        (no-hole-at sq-t8)
        (no-hole-at sq-t9)
        (no-hole-at sq-t10)
        (no-hole-at sq-t11)
        (no-hole-at sq-t12)
        (no-hole-at sq-t13)
        (no-hole-at sq-t14)
        (no-hole-at sq-t15)
        (no-hole-at sq-t16)
        (no-hole-at sq-t17)
        (no-hole-at sq-u1)
        (no-hole-at sq-u2)
        (no-hole-at sq-u3)
        (no-hole-at sq-u4)
        (no-hole-at sq-u5)
        (no-hole-at sq-u6)
        (no-hole-at sq-u7)
        (no-hole-at sq-u8)
        (no-hole-at sq-u9)
        (no-hole-at sq-u10)
        (no-hole-at sq-u11)
        (no-hole-at sq-u12)
        (no-hole-at sq-u13)
        (no-hole-at sq-u14)
        (no-hole-at sq-u15)
        (no-hole-at sq-u16)
        (no-hole-at sq-u17)
        (no-hole-at sq-v1)
        (no-hole-at sq-v2)
        (no-hole-at sq-v3)
        (no-hole-at sq-v4)
        (no-hole-at sq-v5)
        (no-hole-at sq-v6)
        (no-hole-at sq-v7)
        (no-hole-at sq-v8)
        (no-hole-at sq-v9)
        (no-hole-at sq-v10)
        (no-hole-at sq-v11)
        (no-hole-at sq-v12)
        (no-hole-at sq-v13)
        (no-hole-at sq-v14)
        (no-hole-at sq-v15)
        (no-hole-at sq-v16)
        (no-hole-at sq-v17)
        (no-hole-at sq-w1)
        (no-hole-at sq-w2)
        (no-hole-at sq-w3)
        (no-hole-at sq-w4)
        (no-hole-at sq-w5)
        (no-hole-at sq-w6)
        (no-hole-at sq-w7)
        (no-hole-at sq-w8)
        (no-hole-at sq-w9)
        (no-hole-at sq-w10)
        (no-hole-at sq-w11)
        (no-hole-at sq-w12)
        (no-hole-at sq-w13)
        (no-hole-at sq-w14)
        (no-hole-at sq-w15)
        (no-hole-at sq-w16)
        (no-hole-at sq-w17)
        (no-hole-at sq-x1)
        (no-hole-at sq-x2)
        (no-hole-at sq-x3)
        (no-hole-at sq-x4)
        (no-hole-at sq-x5)
        (no-hole-at sq-x6)
        (no-hole-at sq-x7)
        (no-hole-at sq-x8)
        (no-hole-at sq-x9)
        (no-hole-at sq-x10)
        (no-hole-at sq-x11)
        (no-hole-at sq-x12)
        (no-hole-at sq-x13)
        (no-hole-at sq-x14)
        (no-hole-at sq-x15)
        (no-hole-at sq-x16)
        (no-hole-at sq-x17)
        (no-hole-at sq-y1)
        (no-hole-at sq-y2)
        (no-hole-at sq-y3)
        (no-hole-at sq-y4)
        (no-hole-at sq-y5)
        (no-hole-at sq-y6)
        (no-hole-at sq-y7)
        (no-hole-at sq-y8)
        (no-hole-at sq-y9)
        (no-hole-at sq-y10)
        (no-hole-at sq-y11)
        (no-hole-at sq-y12)
        (no-hole-at sq-y13)
        (no-hole-at sq-y14)
        (no-hole-at sq-y15)
        (no-hole-at sq-y16)
        (no-hole-at sq-y17)
        (no-hole-at sq-z1)
        (no-hole-at sq-z2)
        (no-hole-at sq-z3)
        (no-hole-at sq-z4)
        (no-hole-at sq-z5)
        (no-hole-at sq-z6)
        (no-hole-at sq-z7)
        (no-hole-at sq-z8)
        (no-hole-at sq-z9)
        (no-hole-at sq-z10)
        (no-hole-at sq-z11)
        (no-hole-at sq-z12)
        (no-hole-at sq-z13)
        (no-hole-at sq-z14)
        (no-hole-at sq-z15)
        (no-hole-at sq-z16)
        (no-hole-at sq-z17)
        (no-hole-at sq-aa1)
        (no-hole-at sq-aa2)
        (no-hole-at sq-aa3)
        (no-hole-at sq-aa4)
        (no-hole-at sq-aa5)
        (no-hole-at sq-aa6)
        (no-hole-at sq-aa7)
        (no-hole-at sq-aa8)
        (no-hole-at sq-aa9)
        (no-hole-at sq-aa10)
        (no-hole-at sq-aa11)
        (no-hole-at sq-aa12)
        (no-hole-at sq-aa13)
        (no-hole-at sq-aa14)
        (no-hole-at sq-aa15)
        (no-hole-at sq-aa16)
        (no-hole-at sq-aa17)
        (no-hole-at sq-ab1)
        (no-hole-at sq-ab2)
        (no-hole-at sq-ab3)
        (no-hole-at sq-ab4)
        (no-hole-at sq-ab5)
        (no-hole-at sq-ab6)
        (no-hole-at sq-ab7)
        (no-hole-at sq-ab8)
        (no-hole-at sq-ab9)
        (no-hole-at sq-ab10)
        (no-hole-at sq-ab11)
        (no-hole-at sq-ab12)
        (no-hole-at sq-ab13)
        (no-hole-at sq-ab14)
        (no-hole-at sq-ab15)
        (no-hole-at sq-ab16)
        (no-hole-at sq-ab17)
        (no-hole-at sq-ac1)
        (no-hole-at sq-ac2)
        (no-hole-at sq-ac3)
        (no-hole-at sq-ac4)
        (no-hole-at sq-ac5)
        (no-hole-at sq-ac6)
        (no-hole-at sq-ac7)
        (no-hole-at sq-ac8)
        (no-hole-at sq-ac9)
        (no-hole-at sq-ac10)
        (no-hole-at sq-ac11)
        (no-hole-at sq-ac12)
        (no-hole-at sq-ac13)
        (no-hole-at sq-ac14)
        (no-hole-at sq-ac17)
        (no-hole-at sq-ad1)
        (no-hole-at sq-ad2)
        (no-hole-at sq-ad3)
        (no-hole-at sq-ad4)
        (no-hole-at sq-ad5)
        (no-hole-at sq-ad6)
        (no-hole-at sq-ad7)
        (no-hole-at sq-ad8)
        (no-hole-at sq-ad9)
        (no-hole-at sq-ad10)
        (no-hole-at sq-ad11)
        (no-hole-at sq-ad12)
        (no-hole-at sq-ad13)
        (no-hole-at sq-ad14)
        (no-hole-at sq-ad15)
        (no-hole-at sq-ad16)
        (no-hole-at sq-ad17)

        (is-free sq-b3)
        (is-free sq-b4)
        (is-free sq-b14)
        (is-free sq-b15)
        (is-free sq-b16)
        (is-free sq-c3)
        (is-free sq-c4)
        (is-free sq-c9)
        (is-free sq-c10)
        (is-free sq-c12)
        (is-free sq-c13)
        (is-free sq-c14)
        (is-free sq-c16)
        (is-free sq-d3)
        (is-free sq-d4)
        (is-free sq-d5)
        (is-free sq-d6)
        (is-free sq-d7)
        (is-free sq-d8)
        (is-free sq-d9)
        (is-free sq-d10)
        (is-free sq-d12)
        (is-free sq-d14)
        (is-free sq-d15)
        (is-free sq-d16)
        (is-free sq-e4)
        (is-free sq-e8)
        (is-free sq-e9)
        (is-free sq-e10)
        (is-free sq-e12)
        (is-free sq-e13)
        (is-free sq-e14)
        (is-free sq-e15)
        (is-free sq-f4)
        (is-free sq-f6)
        (is-free sq-f7)
        (is-free sq-f8)
        (is-free sq-f15)
        (is-free sq-g4)
        (is-free sq-g6)
        (is-free sq-g7)
        (is-free sq-g8)
        (is-free sq-g9)
        (is-free sq-g10)
        (is-free sq-g11)
        (is-free sq-g12)
        (is-free sq-g13)
        (is-free sq-g15)
        (is-free sq-h2)
        (is-free sq-h3)
        (is-free sq-h4)
        (is-free sq-h11)
        (is-free sq-h13)
        (is-free sq-h15)
        (is-free sq-i2)
        (is-free sq-i3)
        (is-free sq-i4)
        (is-free sq-i5)
        (is-free sq-i6)
        (is-free sq-i7)
        (is-free sq-i11)
        (is-free sq-i12)
        (is-free sq-i13)
        (is-free sq-i15)
        (is-free sq-j3)
        (is-free sq-j5)
        (is-free sq-j7)
        (is-free sq-j15)
        (is-free sq-k3)
        (is-free sq-k5)
        (is-free sq-k6)
        (is-free sq-k7)
        (is-free sq-k8)
        (is-free sq-k9)
        (is-free sq-k10)
        (is-free sq-k15)
        (is-free sq-l3)
        (is-free sq-l5)
        (is-free sq-l7)
        (is-free sq-l9)
        (is-free sq-l10)
        (is-free sq-l15)
        (is-free sq-m3)
        (is-free sq-m5)
        (is-free sq-m6)
        (is-free sq-m7)
        (is-free sq-m9)
        (is-free sq-m15)
        (is-free sq-n3)
        (is-free sq-n9)
        (is-free sq-n12)
        (is-free sq-n13)
        (is-free sq-n15)
        (is-free sq-n16)
        (is-free sq-o3)
        (is-free sq-o5)
        (is-free sq-o6)
        (is-free sq-o7)
        (is-free sq-o8)
        (is-free sq-o9)
        (is-free sq-o11)
        (is-free sq-o12)
        (is-free sq-o13)
        (is-free sq-o14)
        (is-free sq-o15)
        (is-free sq-o16)
        (is-free sq-p3)
        (is-free sq-p5)
        (is-free sq-p6)
        (is-free sq-p8)
        (is-free sq-p9)
        (is-free sq-p11)
        (is-free sq-p12)
        (is-free sq-p14)
        (is-free sq-p15)
        (is-free sq-q3)
        (is-free sq-q6)
        (is-free sq-q12)
        (is-free sq-r3)
        (is-free sq-r4)
        (is-free sq-r6)
        (is-free sq-r7)
        (is-free sq-r8)
        (is-free sq-r9)
        (is-free sq-r10)
        (is-free sq-r12)
        (is-free sq-r14)
        (is-free sq-r15)
        (is-free sq-s3)
        (is-free sq-s4)
        (is-free sq-s6)
        (is-free sq-s7)
        (is-free sq-s9)
        (is-free sq-s10)
        (is-free sq-s12)
        (is-free sq-s14)
        (is-free sq-s16)
        (is-free sq-t3)
        (is-free sq-t9)
        (is-free sq-t12)
        (is-free sq-t14)
        (is-free sq-t15)
        (is-free sq-u3)
        (is-free sq-u5)
        (is-free sq-u6)
        (is-free sq-u7)
        (is-free sq-u8)
        (is-free sq-u9)
        (is-free sq-u12)
        (is-free sq-u14)
        (is-free sq-u15)
        (is-free sq-v3)
        (is-free sq-v5)
        (is-free sq-v6)
        (is-free sq-v8)
        (is-free sq-v9)
        (is-free sq-v12)
        (is-free sq-v15)
        (is-free sq-w3)
        (is-free sq-w6)
        (is-free sq-w12)
        (is-free sq-w13)
        (is-free sq-w15)
        (is-free sq-x3)
        (is-free sq-x4)
        (is-free sq-x6)
        (is-free sq-x7)
        (is-free sq-x8)
        (is-free sq-x9)
        (is-free sq-x10)
        (is-free sq-x11)
        (is-free sq-x12)
        (is-free sq-x13)
        (is-free sq-x15)
        (is-free sq-y3)
        (is-free sq-y4)
        (is-free sq-y6)
        (is-free sq-y7)
        (is-free sq-y12)
        (is-free sq-y15)
        (is-free sq-z3)
        (is-free sq-z9)
        (is-free sq-z10)
        (is-free sq-z12)
        (is-free sq-z15)
        (is-free sq-z16)
        (is-free sq-aa2)
        (is-free sq-aa3)
        (is-free sq-aa5)
        (is-free sq-aa6)
        (is-free sq-aa8)
        (is-free sq-aa9)
        (is-free sq-aa10)
        (is-free sq-aa12)
        (is-free sq-aa13)
        (is-free sq-aa14)
        (is-free sq-aa15)
        (is-free sq-aa16)
        (is-free sq-ab2)
        (is-free sq-ab3)
        (is-free sq-ab4)
        (is-free sq-ab5)
        (is-free sq-ab6)
        (is-free sq-ab7)
        (is-free sq-ab8)
        (is-free sq-ab9)
        (is-free sq-ab10)
        (is-free sq-ab12)
        (is-free sq-ab13)
        (is-free sq-ac3)
        (is-free sq-ac4)
        (is-free sq-ac6)
        (is-free sq-ac7)
        (is-free sq-ac9)
        (is-free sq-ac10)

        (is-wall sq-a2)
        (is-wall sq-a3)
        (is-wall sq-a4)
        (is-wall sq-a5)
        (is-wall sq-a6)
        (is-wall sq-a7)
        (is-wall sq-a8)
        (is-wall sq-a13)
        (is-wall sq-a14)
        (is-wall sq-a15)
        (is-wall sq-a16)
        (is-wall sq-a17)
        (is-wall sq-b2)
        (is-wall sq-b5)
        (is-wall sq-b8)
        (is-wall sq-b9)
        (is-wall sq-b10)
        (is-wall sq-b11)
        (is-wall sq-b12)
        (is-wall sq-b13)
        (is-wall sq-b17)
        (is-wall sq-c2)
        (is-wall sq-c5)
        (is-wall sq-c6)
        (is-wall sq-c7)
        (is-wall sq-c8)
        (is-wall sq-c11)
        (is-wall sq-c15)
        (is-wall sq-c17)
        (is-wall sq-d2)
        (is-wall sq-d11)
        (is-wall sq-d13)
        (is-wall sq-d17)
        (is-wall sq-e1)
        (is-wall sq-e2)
        (is-wall sq-e3)
        (is-wall sq-e5)
        (is-wall sq-e6)
        (is-wall sq-e7)
        (is-wall sq-e11)
        (is-wall sq-e16)
        (is-wall sq-e17)
        (is-wall sq-f1)
        (is-wall sq-f3)
        (is-wall sq-f5)
        (is-wall sq-f9)
        (is-wall sq-f10)
        (is-wall sq-f11)
        (is-wall sq-f12)
        (is-wall sq-f13)
        (is-wall sq-f14)
        (is-wall sq-f16)
        (is-wall sq-g1)
        (is-wall sq-g2)
        (is-wall sq-g3)
        (is-wall sq-g5)
        (is-wall sq-g14)
        (is-wall sq-g16)
        (is-wall sq-h1)
        (is-wall sq-h5)
        (is-wall sq-h6)
        (is-wall sq-h7)
        (is-wall sq-h8)
        (is-wall sq-h9)
        (is-wall sq-h10)
        (is-wall sq-h12)
        (is-wall sq-h14)
        (is-wall sq-h16)
        (is-wall sq-i1)
        (is-wall sq-i8)
        (is-wall sq-i10)
        (is-wall sq-i14)
        (is-wall sq-i16)
        (is-wall sq-j1)
        (is-wall sq-j2)
        (is-wall sq-j4)
        (is-wall sq-j6)
        (is-wall sq-j8)
        (is-wall sq-j9)
        (is-wall sq-j10)
        (is-wall sq-j11)
        (is-wall sq-j12)
        (is-wall sq-j13)
        (is-wall sq-j14)
        (is-wall sq-j16)
        (is-wall sq-k2)
        (is-wall sq-k4)
        (is-wall sq-k11)
        (is-wall sq-k14)
        (is-wall sq-k16)
        (is-wall sq-l2)
        (is-wall sq-l4)
        (is-wall sq-l6)
        (is-wall sq-l8)
        (is-wall sq-l11)
        (is-wall sq-l14)
        (is-wall sq-l16)
        (is-wall sq-m2)
        (is-wall sq-m4)
        (is-wall sq-m8)
        (is-wall sq-m10)
        (is-wall sq-m11)
        (is-wall sq-m12)
        (is-wall sq-m13)
        (is-wall sq-m14)
        (is-wall sq-m16)
        (is-wall sq-m17)
        (is-wall sq-n2)
        (is-wall sq-n4)
        (is-wall sq-n5)
        (is-wall sq-n6)
        (is-wall sq-n7)
        (is-wall sq-n8)
        (is-wall sq-n10)
        (is-wall sq-n11)
        (is-wall sq-n14)
        (is-wall sq-n17)
        (is-wall sq-o2)
        (is-wall sq-o4)
        (is-wall sq-o10)
        (is-wall sq-o17)
        (is-wall sq-p2)
        (is-wall sq-p4)
        (is-wall sq-p7)
        (is-wall sq-p10)
        (is-wall sq-p13)
        (is-wall sq-p16)
        (is-wall sq-p17)
        (is-wall sq-q2)
        (is-wall sq-q4)
        (is-wall sq-q5)
        (is-wall sq-q7)
        (is-wall sq-q8)
        (is-wall sq-q9)
        (is-wall sq-q10)
        (is-wall sq-q11)
        (is-wall sq-q13)
        (is-wall sq-q14)
        (is-wall sq-q15)
        (is-wall sq-q16)
        (is-wall sq-r2)
        (is-wall sq-r5)
        (is-wall sq-r11)
        (is-wall sq-r13)
        (is-wall sq-r16)
        (is-wall sq-r17)
        (is-wall sq-s2)
        (is-wall sq-s5)
        (is-wall sq-s8)
        (is-wall sq-s11)
        (is-wall sq-s13)
        (is-wall sq-s17)
        (is-wall sq-t2)
        (is-wall sq-t4)
        (is-wall sq-t5)
        (is-wall sq-t6)
        (is-wall sq-t7)
        (is-wall sq-t8)
        (is-wall sq-t10)
        (is-wall sq-t11)
        (is-wall sq-t13)
        (is-wall sq-t17)
        (is-wall sq-u2)
        (is-wall sq-u4)
        (is-wall sq-u10)
        (is-wall sq-u11)
        (is-wall sq-u13)
        (is-wall sq-u16)
        (is-wall sq-u17)
        (is-wall sq-v2)
        (is-wall sq-v4)
        (is-wall sq-v7)
        (is-wall sq-v10)
        (is-wall sq-v11)
        (is-wall sq-v13)
        (is-wall sq-v14)
        (is-wall sq-v16)
        (is-wall sq-w2)
        (is-wall sq-w4)
        (is-wall sq-w5)
        (is-wall sq-w7)
        (is-wall sq-w8)
        (is-wall sq-w9)
        (is-wall sq-w10)
        (is-wall sq-w11)
        (is-wall sq-w14)
        (is-wall sq-w16)
        (is-wall sq-x2)
        (is-wall sq-x5)
        (is-wall sq-x14)
        (is-wall sq-x16)
        (is-wall sq-y2)
        (is-wall sq-y5)
        (is-wall sq-y8)
        (is-wall sq-y9)
        (is-wall sq-y10)
        (is-wall sq-y11)
        (is-wall sq-y13)
        (is-wall sq-y14)
        (is-wall sq-y16)
        (is-wall sq-y17)
        (is-wall sq-z1)
        (is-wall sq-z2)
        (is-wall sq-z4)
        (is-wall sq-z5)
        (is-wall sq-z6)
        (is-wall sq-z7)
        (is-wall sq-z8)
        (is-wall sq-z11)
        (is-wall sq-z13)
        (is-wall sq-z14)
        (is-wall sq-z17)
        (is-wall sq-aa1)
        (is-wall sq-aa4)
        (is-wall sq-aa7)
        (is-wall sq-aa11)
        (is-wall sq-aa17)
        (is-wall sq-ab1)
        (is-wall sq-ab11)
        (is-wall sq-ab14)
        (is-wall sq-ab15)
        (is-wall sq-ab16)
        (is-wall sq-ab17)
        (is-wall sq-ac1)
        (is-wall sq-ac2)
        (is-wall sq-ac5)
        (is-wall sq-ac8)
        (is-wall sq-ac11)
        (is-wall sq-ac12)
        (is-wall sq-ac13)
        (is-wall sq-ac14)
        (is-wall sq-ac17)
        (is-wall sq-ad2)
        (is-wall sq-ad3)
        (is-wall sq-ad4)
        (is-wall sq-ad5)
        (is-wall sq-ad6)
        (is-wall sq-ad7)
        (is-wall sq-ad8)
        (is-wall sq-ad9)
        (is-wall sq-ad10)
        (is-wall sq-ad11)
        (is-wall sq-ad14)
        (is-wall sq-ad15)
        (is-wall sq-ad16)
        (is-wall sq-ad17)



        (player-at p1 sq-t16)


        (collected-box b1)
        (collected-box b2)
        (collected-box b3)
        (collected-box b4)
        (collected-box b5)
        (collected-box b6)
        (collected-box b7)
        (collected-box b8)
        (collected-box b10)
        (collected-box b11)

        (has-no-trampoline)
        (= (total-cost) 0)
        (= (collected-coins) 0)
        (= (bombs-available p1) 0)
        (= (pliers-available p1) 10)
    )
    (:goal
        (and
            (collected-box b1)
            (collected-box b2)
            (collected-box b3)
            (collected-box b4)
            (collected-box b5)
            (collected-box b6)
            (collected-box b7)
            (collected-box b8)
            (collected-box b9)
            (collected-box b10)
            (collected-box b11)
            (preference (> (collected-coins) 0))
        )
    )
    (:metric minimize (- (total-cost) (collected-coins)))
)