(define (problem problem_X)
    (:domain sokoban)
    (:objects
        sq-a1 sq-a2 sq-a3 sq-a4 sq-a5 sq-a6 sq-a7 sq-a8 sq-a9 sq-a10 sq-a11 sq-a12 sq-a13 - square
        sq-b1 sq-b2 sq-b3 sq-b4 sq-b5 sq-b6 sq-b7 sq-b8 sq-b9 sq-b10 sq-b11 sq-b12 sq-b13 - square
        sq-c1 sq-c2 sq-c3 sq-c4 sq-c5 sq-c6 sq-c7 sq-c8 sq-c9 sq-c10 sq-c11 sq-c12 sq-c13 - square
        sq-d1 sq-d2 sq-d3 sq-d4 sq-d5 sq-d6 sq-d7 sq-d8 sq-d9 sq-d10 sq-d11 sq-d12 sq-d13 - square
        sq-e1 sq-e2 sq-e3 sq-e4 sq-e5 sq-e6 sq-e7 sq-e8 sq-e9 sq-e10 sq-e11 sq-e12 sq-e13 - square
        sq-f1 sq-f2 sq-f3 sq-f4 sq-f5 sq-f6 sq-f7 sq-f8 sq-f9 sq-f10 sq-f11 sq-f12 sq-f13 - square
        sq-g1 sq-g2 sq-g3 sq-g4 sq-g5 sq-g6 sq-g7 sq-g8 sq-g9 sq-g10 sq-g11 sq-g12 sq-g13 - square
        sq-h1 sq-h2 sq-h3 sq-h4 sq-h5 sq-h6 sq-h7 sq-h8 sq-h9 sq-h10 sq-h11 sq-h12 sq-h13 - square
        sq-i1 sq-i2 sq-i3 sq-i4 sq-i5 sq-i6 sq-i7 sq-i8 sq-i9 sq-i10 sq-i11 sq-i12 sq-i13 - square
        sq-j1 sq-j2 sq-j3 sq-j4 sq-j5 sq-j6 sq-j7 sq-j8 sq-j9 sq-j10 sq-j11 sq-j12 sq-j13 - square
        sq-k1 sq-k2 sq-k3 sq-k4 sq-k5 sq-k6 sq-k7 sq-k8 sq-k9 sq-k10 sq-k11 sq-k12 sq-k13 - square
        sq-l1 sq-l2 sq-l3 sq-l4 sq-l5 sq-l6 sq-l7 sq-l8 sq-l9 sq-l10 sq-l11 sq-l12 sq-l13 - square
        sq-m1 sq-m2 sq-m3 sq-m4 sq-m5 sq-m6 sq-m7 sq-m8 sq-m9 sq-m10 sq-m11 sq-m12 sq-m13 - square
        sq-n1 sq-n2 sq-n3 sq-n4 sq-n5 sq-n6 sq-n7 sq-n8 sq-n9 sq-n10 sq-n11 sq-n12 sq-n13 - square
        sq-o1 sq-o2 sq-o3 sq-o4 sq-o5 sq-o6 sq-o7 sq-o8 sq-o9 sq-o10 sq-o11 sq-o12 sq-o13 - square
        sq-p1 sq-p2 sq-p3 sq-p4 sq-p5 sq-p6 sq-p7 sq-p8 sq-p9 sq-p10 sq-p11 sq-p12 sq-p13 - square
        sq-q1 sq-q2 sq-q3 sq-q4 sq-q5 sq-q6 sq-q7 sq-q8 sq-q9 sq-q10 sq-q11 sq-q12 sq-q13 - square
        b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11 b12 - box
    )

    (:init

        (above sq-a1 sq-a2)
        (above sq-a2 sq-a3)
        (above sq-a3 sq-a4)
        (above sq-a4 sq-a5)
        (above sq-a5 sq-a6)
        (above sq-a6 sq-a7)
        (above sq-a7 sq-a8)
        (above sq-a8 sq-a9)
        (above sq-a9 sq-a10)
        (above sq-a10 sq-a11)
        (above sq-a11 sq-a12)
        (above sq-a12 sq-a13)
        (above sq-b1 sq-b2)
        (above sq-b2 sq-b3)
        (above sq-b3 sq-b4)
        (above sq-b4 sq-b5)
        (above sq-b5 sq-b6)
        (above sq-b6 sq-b7)
        (above sq-b7 sq-b8)
        (above sq-b8 sq-b9)
        (above sq-b9 sq-b10)
        (above sq-b10 sq-b11)
        (above sq-b11 sq-b12)
        (above sq-b12 sq-b13)
        (above sq-c1 sq-c2)
        (above sq-c2 sq-c3)
        (above sq-c3 sq-c4)
        (above sq-c4 sq-c5)
        (above sq-c5 sq-c6)
        (above sq-c6 sq-c7)
        (above sq-c7 sq-c8)
        (above sq-c8 sq-c9)
        (above sq-c9 sq-c10)
        (above sq-c10 sq-c11)
        (above sq-c11 sq-c12)
        (above sq-c12 sq-c13)
        (above sq-d1 sq-d2)
        (above sq-d2 sq-d3)
        (above sq-d3 sq-d4)
        (above sq-d4 sq-d5)
        (above sq-d5 sq-d6)
        (above sq-d6 sq-d7)
        (above sq-d7 sq-d8)
        (above sq-d8 sq-d9)
        (above sq-d9 sq-d10)
        (above sq-d10 sq-d11)
        (above sq-d11 sq-d12)
        (above sq-d12 sq-d13)
        (above sq-e1 sq-e2)
        (above sq-e2 sq-e3)
        (above sq-e3 sq-e4)
        (above sq-e4 sq-e5)
        (above sq-e5 sq-e6)
        (above sq-e6 sq-e7)
        (above sq-e7 sq-e8)
        (above sq-e8 sq-e9)
        (above sq-e9 sq-e10)
        (above sq-e10 sq-e11)
        (above sq-e11 sq-e12)
        (above sq-e12 sq-e13)
        (above sq-f1 sq-f2)
        (above sq-f2 sq-f3)
        (above sq-f3 sq-f4)
        (above sq-f4 sq-f5)
        (above sq-f5 sq-f6)
        (above sq-f6 sq-f7)
        (above sq-f7 sq-f8)
        (above sq-f8 sq-f9)
        (above sq-f9 sq-f10)
        (above sq-f10 sq-f11)
        (above sq-f11 sq-f12)
        (above sq-f12 sq-f13)
        (above sq-g1 sq-g2)
        (above sq-g2 sq-g3)
        (above sq-g3 sq-g4)
        (above sq-g4 sq-g5)
        (above sq-g5 sq-g6)
        (above sq-g6 sq-g7)
        (above sq-g7 sq-g8)
        (above sq-g8 sq-g9)
        (above sq-g9 sq-g10)
        (above sq-g10 sq-g11)
        (above sq-g11 sq-g12)
        (above sq-g12 sq-g13)
        (above sq-h1 sq-h2)
        (above sq-h2 sq-h3)
        (above sq-h3 sq-h4)
        (above sq-h4 sq-h5)
        (above sq-h5 sq-h6)
        (above sq-h6 sq-h7)
        (above sq-h7 sq-h8)
        (above sq-h8 sq-h9)
        (above sq-h9 sq-h10)
        (above sq-h10 sq-h11)
        (above sq-h11 sq-h12)
        (above sq-h12 sq-h13)
        (above sq-i1 sq-i2)
        (above sq-i2 sq-i3)
        (above sq-i3 sq-i4)
        (above sq-i4 sq-i5)
        (above sq-i5 sq-i6)
        (above sq-i6 sq-i7)
        (above sq-i7 sq-i8)
        (above sq-i8 sq-i9)
        (above sq-i9 sq-i10)
        (above sq-i10 sq-i11)
        (above sq-i11 sq-i12)
        (above sq-i12 sq-i13)
        (above sq-j1 sq-j2)
        (above sq-j2 sq-j3)
        (above sq-j3 sq-j4)
        (above sq-j4 sq-j5)
        (above sq-j5 sq-j6)
        (above sq-j6 sq-j7)
        (above sq-j7 sq-j8)
        (above sq-j8 sq-j9)
        (above sq-j9 sq-j10)
        (above sq-j10 sq-j11)
        (above sq-j11 sq-j12)
        (above sq-j12 sq-j13)
        (above sq-k1 sq-k2)
        (above sq-k2 sq-k3)
        (above sq-k3 sq-k4)
        (above sq-k4 sq-k5)
        (above sq-k5 sq-k6)
        (above sq-k6 sq-k7)
        (above sq-k7 sq-k8)
        (above sq-k8 sq-k9)
        (above sq-k9 sq-k10)
        (above sq-k10 sq-k11)
        (above sq-k11 sq-k12)
        (above sq-k12 sq-k13)
        (above sq-l1 sq-l2)
        (above sq-l2 sq-l3)
        (above sq-l3 sq-l4)
        (above sq-l4 sq-l5)
        (above sq-l5 sq-l6)
        (above sq-l6 sq-l7)
        (above sq-l7 sq-l8)
        (above sq-l8 sq-l9)
        (above sq-l9 sq-l10)
        (above sq-l10 sq-l11)
        (above sq-l11 sq-l12)
        (above sq-l12 sq-l13)
        (above sq-m1 sq-m2)
        (above sq-m2 sq-m3)
        (above sq-m3 sq-m4)
        (above sq-m4 sq-m5)
        (above sq-m5 sq-m6)
        (above sq-m6 sq-m7)
        (above sq-m7 sq-m8)
        (above sq-m8 sq-m9)
        (above sq-m9 sq-m10)
        (above sq-m10 sq-m11)
        (above sq-m11 sq-m12)
        (above sq-m12 sq-m13)
        (above sq-n1 sq-n2)
        (above sq-n2 sq-n3)
        (above sq-n3 sq-n4)
        (above sq-n4 sq-n5)
        (above sq-n5 sq-n6)
        (above sq-n6 sq-n7)
        (above sq-n7 sq-n8)
        (above sq-n8 sq-n9)
        (above sq-n9 sq-n10)
        (above sq-n10 sq-n11)
        (above sq-n11 sq-n12)
        (above sq-n12 sq-n13)
        (above sq-o1 sq-o2)
        (above sq-o2 sq-o3)
        (above sq-o3 sq-o4)
        (above sq-o4 sq-o5)
        (above sq-o5 sq-o6)
        (above sq-o6 sq-o7)
        (above sq-o7 sq-o8)
        (above sq-o8 sq-o9)
        (above sq-o9 sq-o10)
        (above sq-o10 sq-o11)
        (above sq-o11 sq-o12)
        (above sq-o12 sq-o13)
        (above sq-p1 sq-p2)
        (above sq-p2 sq-p3)
        (above sq-p3 sq-p4)
        (above sq-p4 sq-p5)
        (above sq-p5 sq-p6)
        (above sq-p6 sq-p7)
        (above sq-p7 sq-p8)
        (above sq-p8 sq-p9)
        (above sq-p9 sq-p10)
        (above sq-p10 sq-p11)
        (above sq-p11 sq-p12)
        (above sq-p12 sq-p13)
        (above sq-q1 sq-q2)
        (above sq-q2 sq-q3)
        (above sq-q3 sq-q4)
        (above sq-q4 sq-q5)
        (above sq-q5 sq-q6)
        (above sq-q6 sq-q7)
        (above sq-q7 sq-q8)
        (above sq-q8 sq-q9)
        (above sq-q9 sq-q10)
        (above sq-q10 sq-q11)
        (above sq-q11 sq-q12)
        (above sq-q12 sq-q13)

        (left-to sq-a1 sq-b1)
        (left-to sq-a2 sq-b2)
        (left-to sq-a3 sq-b3)
        (left-to sq-a4 sq-b4)
        (left-to sq-a5 sq-b5)
        (left-to sq-a6 sq-b6)
        (left-to sq-a7 sq-b7)
        (left-to sq-a8 sq-b8)
        (left-to sq-a9 sq-b9)
        (left-to sq-a10 sq-b10)
        (left-to sq-a11 sq-b11)
        (left-to sq-a12 sq-b12)
        (left-to sq-a13 sq-b13)
        (left-to sq-b1 sq-c1)
        (left-to sq-b2 sq-c2)
        (left-to sq-b3 sq-c3)
        (left-to sq-b4 sq-c4)
        (left-to sq-b5 sq-c5)
        (left-to sq-b6 sq-c6)
        (left-to sq-b7 sq-c7)
        (left-to sq-b8 sq-c8)
        (left-to sq-b9 sq-c9)
        (left-to sq-b10 sq-c10)
        (left-to sq-b11 sq-c11)
        (left-to sq-b12 sq-c12)
        (left-to sq-b13 sq-c13)
        (left-to sq-c1 sq-d1)
        (left-to sq-c2 sq-d2)
        (left-to sq-c3 sq-d3)
        (left-to sq-c4 sq-d4)
        (left-to sq-c5 sq-d5)
        (left-to sq-c6 sq-d6)
        (left-to sq-c7 sq-d7)
        (left-to sq-c8 sq-d8)
        (left-to sq-c9 sq-d9)
        (left-to sq-c10 sq-d10)
        (left-to sq-c11 sq-d11)
        (left-to sq-c12 sq-d12)
        (left-to sq-c13 sq-d13)
        (left-to sq-d1 sq-e1)
        (left-to sq-d2 sq-e2)
        (left-to sq-d3 sq-e3)
        (left-to sq-d4 sq-e4)
        (left-to sq-d5 sq-e5)
        (left-to sq-d6 sq-e6)
        (left-to sq-d7 sq-e7)
        (left-to sq-d8 sq-e8)
        (left-to sq-d9 sq-e9)
        (left-to sq-d10 sq-e10)
        (left-to sq-d11 sq-e11)
        (left-to sq-d12 sq-e12)
        (left-to sq-d13 sq-e13)
        (left-to sq-e1 sq-f1)
        (left-to sq-e2 sq-f2)
        (left-to sq-e3 sq-f3)
        (left-to sq-e4 sq-f4)
        (left-to sq-e5 sq-f5)
        (left-to sq-e6 sq-f6)
        (left-to sq-e7 sq-f7)
        (left-to sq-e8 sq-f8)
        (left-to sq-e9 sq-f9)
        (left-to sq-e10 sq-f10)
        (left-to sq-e11 sq-f11)
        (left-to sq-e12 sq-f12)
        (left-to sq-e13 sq-f13)
        (left-to sq-f1 sq-g1)
        (left-to sq-f2 sq-g2)
        (left-to sq-f3 sq-g3)
        (left-to sq-f4 sq-g4)
        (left-to sq-f5 sq-g5)
        (left-to sq-f6 sq-g6)
        (left-to sq-f7 sq-g7)
        (left-to sq-f8 sq-g8)
        (left-to sq-f9 sq-g9)
        (left-to sq-f10 sq-g10)
        (left-to sq-f11 sq-g11)
        (left-to sq-f12 sq-g12)
        (left-to sq-f13 sq-g13)
        (left-to sq-g1 sq-h1)
        (left-to sq-g2 sq-h2)
        (left-to sq-g3 sq-h3)
        (left-to sq-g4 sq-h4)
        (left-to sq-g5 sq-h5)
        (left-to sq-g6 sq-h6)
        (left-to sq-g7 sq-h7)
        (left-to sq-g8 sq-h8)
        (left-to sq-g9 sq-h9)
        (left-to sq-g10 sq-h10)
        (left-to sq-g11 sq-h11)
        (left-to sq-g12 sq-h12)
        (left-to sq-g13 sq-h13)
        (left-to sq-h1 sq-i1)
        (left-to sq-h2 sq-i2)
        (left-to sq-h3 sq-i3)
        (left-to sq-h4 sq-i4)
        (left-to sq-h5 sq-i5)
        (left-to sq-h6 sq-i6)
        (left-to sq-h7 sq-i7)
        (left-to sq-h8 sq-i8)
        (left-to sq-h9 sq-i9)
        (left-to sq-h10 sq-i10)
        (left-to sq-h11 sq-i11)
        (left-to sq-h12 sq-i12)
        (left-to sq-h13 sq-i13)
        (left-to sq-i1 sq-j1)
        (left-to sq-i2 sq-j2)
        (left-to sq-i3 sq-j3)
        (left-to sq-i4 sq-j4)
        (left-to sq-i5 sq-j5)
        (left-to sq-i6 sq-j6)
        (left-to sq-i7 sq-j7)
        (left-to sq-i8 sq-j8)
        (left-to sq-i9 sq-j9)
        (left-to sq-i10 sq-j10)
        (left-to sq-i11 sq-j11)
        (left-to sq-i12 sq-j12)
        (left-to sq-i13 sq-j13)
        (left-to sq-j1 sq-k1)
        (left-to sq-j2 sq-k2)
        (left-to sq-j3 sq-k3)
        (left-to sq-j4 sq-k4)
        (left-to sq-j5 sq-k5)
        (left-to sq-j6 sq-k6)
        (left-to sq-j7 sq-k7)
        (left-to sq-j8 sq-k8)
        (left-to sq-j9 sq-k9)
        (left-to sq-j10 sq-k10)
        (left-to sq-j11 sq-k11)
        (left-to sq-j12 sq-k12)
        (left-to sq-j13 sq-k13)
        (left-to sq-k1 sq-l1)
        (left-to sq-k2 sq-l2)
        (left-to sq-k3 sq-l3)
        (left-to sq-k4 sq-l4)
        (left-to sq-k5 sq-l5)
        (left-to sq-k6 sq-l6)
        (left-to sq-k7 sq-l7)
        (left-to sq-k8 sq-l8)
        (left-to sq-k9 sq-l9)
        (left-to sq-k10 sq-l10)
        (left-to sq-k11 sq-l11)
        (left-to sq-k12 sq-l12)
        (left-to sq-k13 sq-l13)
        (left-to sq-l1 sq-m1)
        (left-to sq-l2 sq-m2)
        (left-to sq-l3 sq-m3)
        (left-to sq-l4 sq-m4)
        (left-to sq-l5 sq-m5)
        (left-to sq-l6 sq-m6)
        (left-to sq-l7 sq-m7)
        (left-to sq-l8 sq-m8)
        (left-to sq-l9 sq-m9)
        (left-to sq-l10 sq-m10)
        (left-to sq-l11 sq-m11)
        (left-to sq-l12 sq-m12)
        (left-to sq-l13 sq-m13)
        (left-to sq-m1 sq-n1)
        (left-to sq-m2 sq-n2)
        (left-to sq-m3 sq-n3)
        (left-to sq-m4 sq-n4)
        (left-to sq-m5 sq-n5)
        (left-to sq-m6 sq-n6)
        (left-to sq-m7 sq-n7)
        (left-to sq-m8 sq-n8)
        (left-to sq-m9 sq-n9)
        (left-to sq-m10 sq-n10)
        (left-to sq-m11 sq-n11)
        (left-to sq-m12 sq-n12)
        (left-to sq-m13 sq-n13)
        (left-to sq-n1 sq-o1)
        (left-to sq-n2 sq-o2)
        (left-to sq-n3 sq-o3)
        (left-to sq-n4 sq-o4)
        (left-to sq-n5 sq-o5)
        (left-to sq-n6 sq-o6)
        (left-to sq-n7 sq-o7)
        (left-to sq-n8 sq-o8)
        (left-to sq-n9 sq-o9)
        (left-to sq-n10 sq-o10)
        (left-to sq-n11 sq-o11)
        (left-to sq-n12 sq-o12)
        (left-to sq-n13 sq-o13)
        (left-to sq-o1 sq-p1)
        (left-to sq-o2 sq-p2)
        (left-to sq-o3 sq-p3)
        (left-to sq-o4 sq-p4)
        (left-to sq-o5 sq-p5)
        (left-to sq-o6 sq-p6)
        (left-to sq-o7 sq-p7)
        (left-to sq-o8 sq-p8)
        (left-to sq-o9 sq-p9)
        (left-to sq-o10 sq-p10)
        (left-to sq-o11 sq-p11)
        (left-to sq-o12 sq-p12)
        (left-to sq-o13 sq-p13)
        (left-to sq-p1 sq-q1)
        (left-to sq-p2 sq-q2)
        (left-to sq-p3 sq-q3)
        (left-to sq-p4 sq-q4)
        (left-to sq-p5 sq-q5)
        (left-to sq-p6 sq-q6)
        (left-to sq-p7 sq-q7)
        (left-to sq-p8 sq-q8)
        (left-to sq-p9 sq-q9)
        (left-to sq-p10 sq-q10)
        (left-to sq-p11 sq-q11)
        (left-to sq-p12 sq-q12)
        (left-to sq-p13 sq-q13)

        (box-at b1 sq-j7)
        (box-at b2 sq-j8)
        (box-at b3 sq-k6)
        (box-at b4 sq-k10)
        (box-at b5 sq-l3)
        (box-at b6 sq-l7)
        (box-at b7 sq-l9)
        (box-at b8 sq-m7)
        (box-at b9 sq-m8)
        (box-at b10 sq-m10)
        (box-at b11 sq-n6)
        (box-at b12 sq-o4)

        (hole-at sq-b6)
        (hole-at sq-b7)
        (hole-at sq-b8)
        (hole-at sq-c6)
        (hole-at sq-c7)
        (hole-at sq-c8)
        (hole-at sq-d6)
        (hole-at sq-d7)
        (hole-at sq-d8)
        (hole-at sq-e6)
        (hole-at sq-e7)
        (hole-at sq-e8)

        (no-hole-at sq-a1)
        (no-hole-at sq-a2)
        (no-hole-at sq-a3)
        (no-hole-at sq-a4)
        (no-hole-at sq-a5)
        (no-hole-at sq-a6)
        (no-hole-at sq-a7)
        (no-hole-at sq-a8)
        (no-hole-at sq-a9)
        (no-hole-at sq-a10)
        (no-hole-at sq-a11)
        (no-hole-at sq-a12)
        (no-hole-at sq-a13)
        (no-hole-at sq-b1)
        (no-hole-at sq-b2)
        (no-hole-at sq-b3)
        (no-hole-at sq-b4)
        (no-hole-at sq-b5)
        (no-hole-at sq-b9)
        (no-hole-at sq-b10)
        (no-hole-at sq-b11)
        (no-hole-at sq-b12)
        (no-hole-at sq-b13)
        (no-hole-at sq-c1)
        (no-hole-at sq-c2)
        (no-hole-at sq-c3)
        (no-hole-at sq-c4)
        (no-hole-at sq-c5)
        (no-hole-at sq-c9)
        (no-hole-at sq-c10)
        (no-hole-at sq-c11)
        (no-hole-at sq-c12)
        (no-hole-at sq-c13)
        (no-hole-at sq-d1)
        (no-hole-at sq-d2)
        (no-hole-at sq-d3)
        (no-hole-at sq-d4)
        (no-hole-at sq-d5)
        (no-hole-at sq-d9)
        (no-hole-at sq-d10)
        (no-hole-at sq-d11)
        (no-hole-at sq-d12)
        (no-hole-at sq-d13)
        (no-hole-at sq-e1)
        (no-hole-at sq-e2)
        (no-hole-at sq-e3)
        (no-hole-at sq-e4)
        (no-hole-at sq-e5)
        (no-hole-at sq-e9)
        (no-hole-at sq-e10)
        (no-hole-at sq-e11)
        (no-hole-at sq-e12)
        (no-hole-at sq-e13)
        (no-hole-at sq-f1)
        (no-hole-at sq-f2)
        (no-hole-at sq-f3)
        (no-hole-at sq-f4)
        (no-hole-at sq-f5)
        (no-hole-at sq-f6)
        (no-hole-at sq-f7)
        (no-hole-at sq-f8)
        (no-hole-at sq-f9)
        (no-hole-at sq-f10)
        (no-hole-at sq-f11)
        (no-hole-at sq-f12)
        (no-hole-at sq-f13)
        (no-hole-at sq-g1)
        (no-hole-at sq-g2)
        (no-hole-at sq-g3)
        (no-hole-at sq-g4)
        (no-hole-at sq-g5)
        (no-hole-at sq-g6)
        (no-hole-at sq-g7)
        (no-hole-at sq-g8)
        (no-hole-at sq-g9)
        (no-hole-at sq-g10)
        (no-hole-at sq-g11)
        (no-hole-at sq-g12)
        (no-hole-at sq-g13)
        (no-hole-at sq-h1)
        (no-hole-at sq-h2)
        (no-hole-at sq-h3)
        (no-hole-at sq-h4)
        (no-hole-at sq-h5)
        (no-hole-at sq-h6)
        (no-hole-at sq-h7)
        (no-hole-at sq-h8)
        (no-hole-at sq-h9)
        (no-hole-at sq-h10)
        (no-hole-at sq-h11)
        (no-hole-at sq-h12)
        (no-hole-at sq-h13)
        (no-hole-at sq-i1)
        (no-hole-at sq-i2)
        (no-hole-at sq-i3)
        (no-hole-at sq-i4)
        (no-hole-at sq-i5)
        (no-hole-at sq-i6)
        (no-hole-at sq-i7)
        (no-hole-at sq-i8)
        (no-hole-at sq-i9)
        (no-hole-at sq-i10)
        (no-hole-at sq-i11)
        (no-hole-at sq-i12)
        (no-hole-at sq-i13)
        (no-hole-at sq-j1)
        (no-hole-at sq-j2)
        (no-hole-at sq-j3)
        (no-hole-at sq-j4)
        (no-hole-at sq-j5)
        (no-hole-at sq-j6)
        (no-hole-at sq-j7)
        (no-hole-at sq-j8)
        (no-hole-at sq-j9)
        (no-hole-at sq-j10)
        (no-hole-at sq-j11)
        (no-hole-at sq-j12)
        (no-hole-at sq-j13)
        (no-hole-at sq-k1)
        (no-hole-at sq-k2)
        (no-hole-at sq-k3)
        (no-hole-at sq-k4)
        (no-hole-at sq-k5)
        (no-hole-at sq-k6)
        (no-hole-at sq-k7)
        (no-hole-at sq-k8)
        (no-hole-at sq-k9)
        (no-hole-at sq-k10)
        (no-hole-at sq-k11)
        (no-hole-at sq-k12)
        (no-hole-at sq-k13)
        (no-hole-at sq-l1)
        (no-hole-at sq-l2)
        (no-hole-at sq-l3)
        (no-hole-at sq-l4)
        (no-hole-at sq-l5)
        (no-hole-at sq-l6)
        (no-hole-at sq-l7)
        (no-hole-at sq-l8)
        (no-hole-at sq-l9)
        (no-hole-at sq-l10)
        (no-hole-at sq-l11)
        (no-hole-at sq-l12)
        (no-hole-at sq-l13)
        (no-hole-at sq-m1)
        (no-hole-at sq-m2)
        (no-hole-at sq-m3)
        (no-hole-at sq-m4)
        (no-hole-at sq-m5)
        (no-hole-at sq-m6)
        (no-hole-at sq-m7)
        (no-hole-at sq-m8)
        (no-hole-at sq-m9)
        (no-hole-at sq-m10)
        (no-hole-at sq-m11)
        (no-hole-at sq-m12)
        (no-hole-at sq-m13)
        (no-hole-at sq-n1)
        (no-hole-at sq-n2)
        (no-hole-at sq-n3)
        (no-hole-at sq-n4)
        (no-hole-at sq-n5)
        (no-hole-at sq-n6)
        (no-hole-at sq-n7)
        (no-hole-at sq-n8)
        (no-hole-at sq-n9)
        (no-hole-at sq-n10)
        (no-hole-at sq-n11)
        (no-hole-at sq-n12)
        (no-hole-at sq-n13)
        (no-hole-at sq-o1)
        (no-hole-at sq-o2)
        (no-hole-at sq-o3)
        (no-hole-at sq-o4)
        (no-hole-at sq-o5)
        (no-hole-at sq-o6)
        (no-hole-at sq-o7)
        (no-hole-at sq-o8)
        (no-hole-at sq-o9)
        (no-hole-at sq-o10)
        (no-hole-at sq-o11)
        (no-hole-at sq-o12)
        (no-hole-at sq-o13)
        (no-hole-at sq-p1)
        (no-hole-at sq-p2)
        (no-hole-at sq-p3)
        (no-hole-at sq-p4)
        (no-hole-at sq-p5)
        (no-hole-at sq-p6)
        (no-hole-at sq-p7)
        (no-hole-at sq-p8)
        (no-hole-at sq-p9)
        (no-hole-at sq-p10)
        (no-hole-at sq-p11)
        (no-hole-at sq-p12)
        (no-hole-at sq-p13)
        (no-hole-at sq-q1)
        (no-hole-at sq-q2)
        (no-hole-at sq-q3)
        (no-hole-at sq-q4)
        (no-hole-at sq-q5)
        (no-hole-at sq-q6)
        (no-hole-at sq-q7)
        (no-hole-at sq-q8)
        (no-hole-at sq-q9)
        (no-hole-at sq-q10)
        (no-hole-at sq-q11)
        (no-hole-at sq-q12)
        (no-hole-at sq-q13)

        (is-free sq-b6)
        (is-free sq-b7)
        (is-free sq-b8)
        (is-free sq-c6)
        (is-free sq-c7)
        (is-free sq-c8)
        (is-free sq-d6)
        (is-free sq-d7)
        (is-free sq-d8)
        (is-free sq-e6)
        (is-free sq-e7)
        (is-free sq-e8)
        (is-free sq-f6)
        (is-free sq-f7)
        (is-free sq-f8)
        (is-free sq-g6)
        (is-free sq-g7)
        (is-free sq-g8)
        (is-free sq-h7)
        (is-free sq-i7)
        (is-free sq-j2)
        (is-free sq-j3)
        (is-free sq-j4)
        (is-free sq-j5)
        (is-free sq-j6)
        (is-free sq-j9)
        (is-free sq-j10)
        (is-free sq-k2)
        (is-free sq-k4)
        (is-free sq-k7)
        (is-free sq-k8)
        (is-free sq-k9)
        (is-free sq-l2)
        (is-free sq-l4)
        (is-free sq-l6)
        (is-free sq-l8)
        (is-free sq-l10)
        (is-free sq-l11)
        (is-free sq-l12)
        (is-free sq-m4)
        (is-free sq-m6)
        (is-free sq-m9)
        (is-free sq-m12)
        (is-free sq-n4)
        (is-free sq-n5)
        (is-free sq-n7)
        (is-free sq-n8)
        (is-free sq-n9)
        (is-free sq-n10)
        (is-free sq-n12)
        (is-free sq-o3)
        (is-free sq-o5)
        (is-free sq-o10)
        (is-free sq-o11)
        (is-free sq-o12)
        (is-free sq-p3)
        (is-free sq-p4)
        (is-free sq-p5)

        (is-wall sq-a5)
        (is-wall sq-a6)
        (is-wall sq-a7)
        (is-wall sq-a8)
        (is-wall sq-a9)
        (is-wall sq-b5)
        (is-wall sq-b9)
        (is-wall sq-c5)
        (is-wall sq-c9)
        (is-wall sq-d5)
        (is-wall sq-d9)
        (is-wall sq-e5)
        (is-wall sq-e9)
        (is-wall sq-f5)
        (is-wall sq-f9)
        (is-wall sq-g5)
        (is-wall sq-g9)
        (is-wall sq-h5)
        (is-wall sq-h6)
        (is-wall sq-h8)
        (is-wall sq-h9)
        (is-wall sq-i1)
        (is-wall sq-i2)
        (is-wall sq-i3)
        (is-wall sq-i4)
        (is-wall sq-i5)
        (is-wall sq-i6)
        (is-wall sq-i8)
        (is-wall sq-i9)
        (is-wall sq-i10)
        (is-wall sq-i11)
        (is-wall sq-j1)
        (is-wall sq-j11)
        (is-wall sq-k1)
        (is-wall sq-k3)
        (is-wall sq-k5)
        (is-wall sq-k11)
        (is-wall sq-k12)
        (is-wall sq-k13)
        (is-wall sq-l1)
        (is-wall sq-l5)
        (is-wall sq-l13)
        (is-wall sq-m1)
        (is-wall sq-m2)
        (is-wall sq-m3)
        (is-wall sq-m5)
        (is-wall sq-m11)
        (is-wall sq-m13)
        (is-wall sq-n2)
        (is-wall sq-n3)
        (is-wall sq-n11)
        (is-wall sq-n13)
        (is-wall sq-o2)
        (is-wall sq-o6)
        (is-wall sq-o7)
        (is-wall sq-o9)
        (is-wall sq-o13)
        (is-wall sq-p2)
        (is-wall sq-p6)
        (is-wall sq-p7)
        (is-wall sq-p8)
        (is-wall sq-p9)
        (is-wall sq-p10)
        (is-wall sq-p11)
        (is-wall sq-p12)
        (is-wall sq-p13)
        (is-wall sq-q2)
        (is-wall sq-q3)
        (is-wall sq-q4)
        (is-wall sq-q5)
        (is-wall sq-q6)



        (player-at p1 sq-o8)



        (has-no-trampoline)
        (= (time) 0)
        (= (collected-coins) 0)
        (= (bombs-available p1) 0)
        (= (pliers-available p1) 0)
    )
    (:goal
        (and
            (collected-box b1)
            (collected-box b2)
            (collected-box b3)
            (collected-box b4)
            (collected-box b5)
            (collected-box b6)
            (collected-box b7)
            (collected-box b8)
            (collected-box b9)
            (collected-box b10)
            (collected-box b11)
            (collected-box b12)
        )
    )
)